project:
  type: book
  output-dir: docs
  
book:
  title: "Statistical Learning"
  subtitle: "Beyond the Numbers"
  author: "Oliver Schabenberger"
  date: "8/01/2024"
  reader-mode: true

  page-footer:
    left: |
      Statistical Learning by Oliver Schabenberger
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: SLCover.png

  chapters:
    - index.qmd  # the preface
    - intro.qmd

    - part: "Part I. Foundation"
      chapters:
        - statmodels.qmd
        - biasvariance.qmd
        - linalg.qmd
        - estimation.qmd 
        - learningtypes.qmd

    - part: "Part II. Supervised Learning I: Regression"
      chapters:
         - regintro.qmd
         - regglobal.qmd
         - regfeature.qmd
         - regnlr.qmd 
         - regdiscrete.qmd
         - reglocal.qmd

    - part: "Part III. Supervised Learning II: Classification"
      chapters:
        - class_reg.qmd
        - discriminant.qmd
        - naivebayes.qmd
        - supportvectors.qmd
    
    - part: "Part IV. Decision Trees"
#        - decisiontrees.qmd
    
    - part: "Part V. Ensemble Methods"
      chapters:
         - ensemble_intro.qmd
         - bagging.qmd
         - boosting.qmd
         - bma.qmd
#        - stacking.qmd

    - part: "Part VI. Unsupervised Learning"
      chapters:
        - unsuper_intro.qmd
        - pca.qmd
        - clustering.qmd
        - mbc.qmd
        - arules.qmd

    - part: "Part VII. Supervised Learning III: Advanced Topics"
      chapters:
         - glm.qmd
         - gam.qmd
         - corrdata.qmd
         - mixed.qmd

    - part: "Part VIII. Neural Networks and Deep Learning"
      chapters:
        - ann.qmd
        - training_ann.qmd
        - ann_R.qmd
        - deeplearning.qmd
        - reinforcement.qmd
    
    - part: "Part IX. Explainability"
      chapters:
        - explainability.qmd
        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo,customstyle.scss]
        dark: [slate,customstyle.scss]
 #   embed-resources: true
    smooth-scroll: true
    number-sections: true
    number-depth: 2
    toc-depth: 4
    toc-expand: 2
    pdf:
    documentclass: scrreprt
#    include-in-header: latexmacros.tex

# editor: visual
