<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Learning - 33&nbsp; Neural Networks in R (with Keras)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./deeplearning.html" rel="next">
<link href="./training_ann.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ann.html">Part VIII. Neural Networks and Deep Learning</a></li><li class="breadcrumb-item"><a href="./ann_R.html"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Neural Networks in <code>R</code> (with Keras)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Learning</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Part I. Foundation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statmodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./biasvariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bias Variance Tradeoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linalg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Algebra Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Parameter Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./learningtypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Statistical Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Part II. Supervised Learning I: Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regintro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regglobal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Classical Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regfeature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Feature Selection and Regularization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regnlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Nonlinear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regdiscrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Discrete Target Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reglocal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Local Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Part III. Supervised Learning II: Classification</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classintro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./class_reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regression Approach to Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./class_random.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Classification with Random Inputs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./supportvectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Support Vectors</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Part IV. Decision Trees</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decisiontrees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Regression and Classification Trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./treesinR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Trees in <code>R</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Part V. Ensemble Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ensemble_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bagging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Bagging</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./boosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Boosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Bayesian Model Averaging</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Part VI. Unsupervised Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unsuper_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Principal Component Analysis (PCA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Cluster Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mbc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Model-based Clustering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Association Rules</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Part VII. Supervised Learning III: Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Generalized Additive Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./corrdata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlated Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Mixed Models for Longitudinal Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">Part VIII. Neural Networks and Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Artificial Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./training_ann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Training Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ann_R.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Neural Networks in <code>R</code> (with Keras)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./deeplearning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Deep Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reinforcement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Reinforcement Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Part IX. Explainability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explainability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Interpretability and Explainability</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">33.1</span> Introduction</a></li>
  <li><a href="#running-keras-in-r" id="toc-running-keras-in-r" class="nav-link" data-scroll-target="#running-keras-in-r"><span class="header-section-number">33.2</span> Running Keras in <code>R</code></a>
  <ul>
  <li><a href="#installation" id="toc-installation" class="nav-link" data-scroll-target="#installation">Installation</a></li>
  <li><a href="#keras-basics" id="toc-keras-basics" class="nav-link" data-scroll-target="#keras-basics">Keras Basics</a>
  <ul class="collapse">
  <li><a href="#defining-the-network" id="toc-defining-the-network" class="nav-link" data-scroll-target="#defining-the-network">Defining the network</a></li>
  <li><a href="#setting-up-the-optimization" id="toc-setting-up-the-optimization" class="nav-link" data-scroll-target="#setting-up-the-optimization">Setting up the optimization</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">Fitting the model</a></li>
  <li><a href="#random-numbers" id="toc-random-numbers" class="nav-link" data-scroll-target="#random-numbers">Random numbers</a></li>
  </ul></li>
  <li><a href="#sec-mnist-analysis-ann" id="toc-sec-mnist-analysis-ann" class="nav-link" data-scroll-target="#sec-mnist-analysis-ann">MNIST Image Classification</a>
  <ul class="collapse">
  <li><a href="#setup-the-data" id="toc-setup-the-data" class="nav-link" data-scroll-target="#setup-the-data">Setup the data</a></li>
  <li><a href="#multi-layer-neural-network" id="toc-multi-layer-neural-network" class="nav-link" data-scroll-target="#multi-layer-neural-network">Multi layer neural network</a></li>
  <li><a href="#sec-ann-multinomial" id="toc-sec-ann-multinomial" class="nav-link" data-scroll-target="#sec-ann-multinomial">Multinomial logistic regression</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ann.html">Part VIII. Neural Networks and Deep Learning</a></li><li class="breadcrumb-item"><a href="./ann_R.html"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Neural Networks in <code>R</code> (with Keras)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Neural Networks in <code>R</code> (with Keras)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="33.1">
<h2 data-number="33.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">33.1</span> Introduction</h2>
<p>Working with neural networks in <code>R</code> can be a bit challenging. For one, there are many packages available that can train ANNs, see <a href="#tbl-ann-R-packages" class="quarto-xref">Table&nbsp;<span>33.1</span></a> for some examples. The packages vary greatly in capabilities and syntax.</p>
<p>Several frameworks for ANNs and deep learning exist. <a href="https://www.tensorflow.org/">TensorFlow</a>, <a href="https://learn.microsoft.com/en-us/archive/msdn-magazine/2017/july/machine-learning-introduction-to-the-microsoft-cntk-v2-0-library">Microsoft CNTK</a>, <a href="https://pytorch.org/">PyTorch</a>, and <a href="https://pypi.org/project/Theano/">Theano</a> are among the most important ones.</p>
<div id="tbl-ann-R-packages" class="striped quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ann-R-packages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;33.1: Some <code>R</code> packages for neural network analysis.
</figcaption>
<div aria-describedby="tbl-ann-R-packages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table">
<colgroup>
<col style="width: 34%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>nnet</code></td>
<td>Feed-forward neural networks with a single hidden layer, and for multinomial log-linear models</td>
</tr>
<tr class="even">
<td><code>neuralnet</code></td>
<td>Training of neural networks using backpropagation</td>
</tr>
<tr class="odd">
<td><code>tensorflow</code></td>
<td>Interface to TensorFlow, a free and open-source software library for machine learning and artificial intelligence</td>
</tr>
<tr class="even">
<td><code>darch</code></td>
<td>Deep architectures and Restricted Boltzmann Machines</td>
</tr>
<tr class="odd">
<td><code>deepnet</code></td>
<td>Deep learning toolkit</td>
</tr>
<tr class="even">
<td><code>deepr</code></td>
<td>Streamlines training, tuning, and predicting for deep learning based on <code>darch</code> and <code>deepnet</code></td>
</tr>
<tr class="odd">
<td><code>rnn</code></td>
<td>Recurrent Neural Networks (RNN)</td>
</tr>
<tr class="even">
<td><code>torch</code></td>
<td>Tensors and neural networks with GPU acceleration; similar to Pytorch</td>
</tr>
<tr class="odd">
<td><code>keras</code></td>
<td>Interface to the Python deep learning library Keras</td>
</tr>
<tr class="even">
<td><code>kerasR</code></td>
<td>Interface to the Python deep learning library Keras</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="https://keras.io/">Keras</a> has emerged as an important API (Application Programming Interface) for deep learning. It provides a consistent interface on top of JAX, TensorFlow, or PyTorch. While TensorFlow is very powerful, the learning curve can be steep and you tend to write a lot of code. On the other hand, you have complete control over the types of models you build and train with TensorFlow. That makes Keras so relevant: you can tap into the capabilities of TensorFlow with a simpler API.</p>
<p>The drawback of using Keras and other deep learning frameworks in <code>R</code> is that they are written in Python. Tools from the modern machine learning toolbox tend to be written in Python. The <code>keras</code> package in <code>R</code> is not an implementation of Keras in <code>R</code>, it is an R-based API that calls into the Keras Python code. And that code calls into Tensorflow, or whatever deep learning framework Keras is running on.</p>
<p>To use <code>keras</code> in <code>R</code>, you thus need to manage a Python distribution, manage Python packages, and deal with the idiosyncrasies of function interfaces between programming languages. For example, you will have to deal with Python error messages bubbling up to the <code>R</code> session. Fortunately, some of the headaches of running Python from <code>R</code> are mitigated by the <code>reticulate</code> package which provides the <code>R</code> interface to Python.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>KerasR</code> package is not the same as the <code>keras</code> package in <code>R</code>. Both packages provide an API for Keras and the API of <code>KerasR</code> is closer to the Python syntax. That makes switching between <code>R</code> and Python for deep learning easier. However, the <code>keras</code> package supports piping of operations similar to the <code>dplyr</code> package. I find working with <code>keras</code> simple because neural networks can be build by piping layer definitions. After all, that is how neural networks work: the output of one layer is input to the next layer.</p>
</div>
</div>
<p>We will be using the <code>keras</code> package in <code>R</code>. It uses the TensorFlow framework under the cover by default.</p>
</section>
<section id="running-keras-in-r" class="level2" data-number="33.2">
<h2 data-number="33.2" class="anchored" data-anchor-id="running-keras-in-r"><span class="header-section-number">33.2</span> Running Keras in <code>R</code></h2>
<section id="installation" class="level3">
<h3 class="anchored" data-anchor-id="installation">Installation</h3>
<p>As mentioned earlier, running <code>keras</code> requires a Python distribution. In addition, you need to install the Keras and TensorFlow Python libraries. The preferred Python installation in this case is conda-based. Good instructions for installing TensorFlow, Keras, and the Python runtime at once—depending on whether you have a prior conda installation—can be found <a href="https://hastie.su.domains/ISLR2/keras-instructions.html">here</a>.</p>
<p>In the situation without prior conda installation, these commands will install everything you need (do this once in your environment):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"keras"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>reticulate<span class="sc">::</span><span class="fu">install_miniconda</span>()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>keras<span class="sc">::</span><span class="fu">install_keras</span>(<span class="at">method=</span><span class="st">"conda"</span>, <span class="at">python_version=</span><span class="st">"3.11"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, in an <code>R</code> session that runs <code>keras</code> do the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(keras)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>reticulate<span class="sc">::</span><span class="fu">use_condaenv</span>(<span class="at">condaenv =</span> <span class="st">"r-tensorflow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>"r-tensorflow"</code> conda environment was installed during the previous step.</p>
</section>
<section id="keras-basics" class="level3">
<h3 class="anchored" data-anchor-id="keras-basics">Keras Basics</h3>
<p>Training a neural network with <code>keras</code> involves three steps:</p>
<ol type="1">
<li><p>Defining the network</p></li>
<li><p>Setting up the optimization</p></li>
<li><p>Fitting the model</p></li>
</ol>
<p>Not until the third step does the algorithm get in contact with actual data. However, we need to know some things about the data in order to define the network in step 1: the dimensions of the input and output.</p>
<section id="defining-the-network" class="level4">
<h4 class="anchored" data-anchor-id="defining-the-network">Defining the network</h4>
<p>The most convenient way of specifying a multi layer neural network is by adding layers sequentially, from the input layer to the output layer. These starts with a call to <code>keras_model_sequential()</code>. Suppose we want to predict a continuous response (regression application) based on inputs <span class="math inline">\(x_1, \cdots, x_{20}\)</span> with one hidden layer and dropout regularization.</p>
<p>The following statements define the model sequentially:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>firstANN <span class="ot">&lt;-</span> <span class="fu">keras_model_sequential</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dense</span>(<span class="at">units      =</span><span class="dv">50</span>, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">activation =</span><span class="st">"relu"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">input_shape=</span><span class="dv">20</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                ) <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dropout</span>(<span class="at">rate=</span><span class="fl">0.4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">1</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">name =</span><span class="st">"Output"</span>)             </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>layer_dense()</code> adds a fully connected layer to the networks, the <code>units=</code> option specifies the number of neurons in the layer. The <code>input_shape=</code> option is specified only for the first layer in the network. In summary, the hidden layer receives 20 inputs and has 50 output units (neurons) and ReLU activation. The output from the hidden layer is passed on (piped) to a dropout layer with a dropout rate of <span class="math inline">\(\phi = 0.4\)</span>. The result of the dropout layer is passed on to another fully connected layer with a single neuron. This is the output layer of the network. In other words, the last layer in the sequence is automatically the output layer. Since we are in a regression context to predict a numeric target variable, there is only one output unit in the final layer. If this was a classification problem with <span class="math inline">\(5\)</span> categories, the last layer would have 5 units.</p>
<p>You can assign a name to each layer with the <code>name=</code> option, this makes it easier to identify the layers in output. If you do not specify a name, Keras will assign a name that combines a description of the layer type with a numerical index (not always). The numeric indices can be confusing because they depend on counters internal to the Python code. Assigning an explicit name is recommended practice.</p>
<p>The <code>activation=</code> option specifies the activation function <span class="math inline">\(\sigma()\)</span> for the hidden layers and the output function <span class="math inline">\(g()\)</span> for the output layer. The default is the identity (“linear”) activation, <span class="math inline">\(\sigma(x) = x\)</span>. This default is appropriate for the output layer in a regression application. For the hidden layer we choose the ReLU activation.</p>
<p>To see the list of activation functions supported by <code>keras</code> (Keras), type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>?keras<span class="sc">::</span>acti</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>at the console prompt.</p>
<p>The basic neural network is now defined and we can find out how many parameters it entails.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(firstANN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model: "sequential"
________________________________________________________________________________
 Layer (type)                       Output Shape                    Param #     
================================================================================
 dense (Dense)                      (None, 50)                      1050        
 dropout (Dropout)                  (None, 50)                      0           
 Output (Dense)                     (None, 1)                       51          
================================================================================
Total params: 1101 (4.30 KB)
Trainable params: 1101 (4.30 KB)
Non-trainable params: 0 (0.00 Byte)
________________________________________________________________________________</code></pre>
</div>
</div>
<p>With 20 inputs and 50 neurons, the first layer has 50 x 21 = 1050 parameters (20 slopes and an intercept for each output neuron). The dropout layer does not add any parameters to the estimation, it chooses output neurons of the previous layer at random and sets their activation to zero. The 50 neurons (some with activation set randomly to zero) are the input to the final layer, adding fifty weights (slopes) and one bias (intercept). The total number of parameters of this neural network is 1,101.</p>
</section>
<section id="setting-up-the-optimization" class="level4">
<h4 class="anchored" data-anchor-id="setting-up-the-optimization">Setting up the optimization</h4>
<p>The second step in training a model in Keras is to specify the particulars of the optimization with the <code>keras::compile()</code> function (which actually calls <code>keras::compile.keras.engine.training.Model</code>). Typical specifications include the loss functions, the type of optimization algorithm, and the metrics evaluated by the model during training.</p>
<p>The following function call uses the RMSProp algorithm with mean-squared error loss function to estimate the parameters of the network. During training, the mean absolute error is also monitored in addition to the mean squared error.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>firstANN <span class="sc">%&gt;%</span> <span class="fu">compile</span>(<span class="at">loss=</span><span class="st">"mse"</span>,                         <span class="co"># see keras$losses$</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">optimizer=</span><span class="fu">optimizer_rmsprop</span>(),      <span class="co"># see keras$optimizers$</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">metrics=</span><span class="fu">list</span>(<span class="st">"mean_absolute_error"</span>) <span class="co"># see keras$metrics$</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>   )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Depending on your environment, not all optimization algorithms are supported.</p>
</section>
<section id="fitting-the-model" class="level4">
<h4 class="anchored" data-anchor-id="fitting-the-model">Fitting the model</h4>
<p>The last step in training the network is to connect the defined and compiled model with training—and possibly test—data.</p>
<p>For this example we use the <code>Hitters</code> data from the ISLR2 package. This is a data set with 322 observations of major league baseball players from the 1986 and 1987 seasons. The following code removes observations with missing values from the data frame, defines a vector of ids for the test data (1/3 of the observations) and computes a scaled and centered model matrix using all 20 input variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>Gitters <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(Hitters)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(Gitters)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">13</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>ntest <span class="ot">&lt;-</span> <span class="fu">trunc</span>(n <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>testid <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, ntest)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">scale</span>(<span class="fu">model.matrix</span>(Salary <span class="sc">~</span> . <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> Gitters))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> Gitters<span class="sc">$</span>Salary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that the model contains several factors (<code>League</code>, <code>Division</code>, <code>NewLeague</code>) whose levels are encoded as binary variables in the model matrix. One could exclude those from scaling and centering as they already are in the proper range. In a regression model you would not want to scale these variables to preserve the interpretation of their coefficients. In a neural network interpretation of the model coefficients is not important and we include all columns of the model matrix in the scaling operation.</p>
<p>The following code fits the model to the training data (<code>-testid</code>) using 20 <strong>epochs</strong> and a minibatch size of 32. That means the gradient is computed based on 32 randomly chosen observations in each step of the stochastic gradient descent algorithm. Since there are 176 training observations it takes <span class="math inline">\(176/32=5.5\)</span> SGD steps to process all <span class="math inline">\(n\)</span> observations. This is known as an <strong>epoch</strong> and is akin to the concept of an <strong>iteration</strong> in numerical optimization: a full pass through the data. The fundamental difference between an epoch and an iteration lies in the fact that updates of the parameters occur after each gradient computation. In a full iteration, there is one update after the pass through the entire data. In SGD with minibatch, there are multiple updates of the parameters, one for each minibatch.</p>
<p>Running 200 epochs with a batch size of 32 and a training set size of 176 results in 200 * 5.5 = 1,100 gradient evaluations.</p>
<p>The <code>validation_data=</code> option lists the test data for the training. The objective function and metrics specified in the <code>compile</code> command earlier are computed at each epoch for the training and the test data if the latter is specified. If you do not have a validation data set, you can specify <code>validation_split=</code> and request that a fraction of the training data is held back for validation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>history <span class="ot">&lt;-</span> firstANN <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(x[<span class="sc">-</span>testid, ], </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        y[<span class="sc">-</span>testid  ], </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">epochs=</span><span class="dv">200</span>, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">batch_size=</span><span class="dv">32</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">validation_data=</span><span class="fu">list</span>(x[testid, ], y[testid])</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/200
6/6 - 0s - loss: 457123.4062 - mean_absolute_error: 533.7993 - val_loss: 555921.1250 - val_mean_absolute_error: 539.5566 - 270ms/epoch - 45ms/step
Epoch 2/200
6/6 - 0s - loss: 456602.7188 - mean_absolute_error: 533.4498 - val_loss: 555512.3125 - val_mean_absolute_error: 539.3163 - 21ms/epoch - 4ms/step
Epoch 3/200
6/6 - 0s - loss: 456319.0312 - mean_absolute_error: 533.1907 - val_loss: 555153.8125 - val_mean_absolute_error: 539.1015 - 12ms/epoch - 2ms/step
Epoch 4/200
6/6 - 0s - loss: 456100.3125 - mean_absolute_error: 533.0711 - val_loss: 554822.5000 - val_mean_absolute_error: 538.8998 - 11ms/epoch - 2ms/step
Epoch 5/200
6/6 - 0s - loss: 455700.9688 - mean_absolute_error: 532.8115 - val_loss: 554482.1250 - val_mean_absolute_error: 538.6848 - 11ms/epoch - 2ms/step
Epoch 6/200
6/6 - 0s - loss: 455458.5938 - mean_absolute_error: 532.6063 - val_loss: 554150.1875 - val_mean_absolute_error: 538.4880 - 12ms/epoch - 2ms/step
Epoch 7/200
6/6 - 0s - loss: 455174.6250 - mean_absolute_error: 532.3958 - val_loss: 553797.6250 - val_mean_absolute_error: 538.2800 - 11ms/epoch - 2ms/step
Epoch 8/200
6/6 - 0s - loss: 454783.2812 - mean_absolute_error: 532.0899 - val_loss: 553442.0625 - val_mean_absolute_error: 538.0660 - 11ms/epoch - 2ms/step
Epoch 9/200
6/6 - 0s - loss: 454540.7812 - mean_absolute_error: 531.9774 - val_loss: 553114.0625 - val_mean_absolute_error: 537.8616 - 11ms/epoch - 2ms/step
Epoch 10/200
6/6 - 0s - loss: 454101.3125 - mean_absolute_error: 531.6488 - val_loss: 552767.0625 - val_mean_absolute_error: 537.6472 - 11ms/epoch - 2ms/step
Epoch 11/200
6/6 - 0s - loss: 454008.8750 - mean_absolute_error: 531.5083 - val_loss: 552423.9375 - val_mean_absolute_error: 537.4375 - 11ms/epoch - 2ms/step
Epoch 12/200
6/6 - 0s - loss: 453537.7188 - mean_absolute_error: 531.2760 - val_loss: 552037.4375 - val_mean_absolute_error: 537.2047 - 11ms/epoch - 2ms/step
Epoch 13/200
6/6 - 0s - loss: 453338.1250 - mean_absolute_error: 531.0852 - val_loss: 551663.2500 - val_mean_absolute_error: 536.9808 - 11ms/epoch - 2ms/step
Epoch 14/200
6/6 - 0s - loss: 452944.6875 - mean_absolute_error: 530.9225 - val_loss: 551242.9375 - val_mean_absolute_error: 536.7334 - 11ms/epoch - 2ms/step
Epoch 15/200
6/6 - 0s - loss: 452406.3750 - mean_absolute_error: 530.4628 - val_loss: 550830.8750 - val_mean_absolute_error: 536.4860 - 11ms/epoch - 2ms/step
Epoch 16/200
6/6 - 0s - loss: 452446.0312 - mean_absolute_error: 530.4238 - val_loss: 550452.8125 - val_mean_absolute_error: 536.2599 - 11ms/epoch - 2ms/step
Epoch 17/200
6/6 - 0s - loss: 451480.8750 - mean_absolute_error: 529.8994 - val_loss: 550011.1875 - val_mean_absolute_error: 535.9950 - 11ms/epoch - 2ms/step
Epoch 18/200
6/6 - 0s - loss: 451614.2188 - mean_absolute_error: 529.8461 - val_loss: 549574.8750 - val_mean_absolute_error: 535.7400 - 11ms/epoch - 2ms/step
Epoch 19/200
6/6 - 0s - loss: 451221.1250 - mean_absolute_error: 529.5458 - val_loss: 549151.5625 - val_mean_absolute_error: 535.4875 - 14ms/epoch - 2ms/step
Epoch 20/200
6/6 - 0s - loss: 450746.5312 - mean_absolute_error: 529.2984 - val_loss: 548681.5000 - val_mean_absolute_error: 535.2109 - 11ms/epoch - 2ms/step
Epoch 21/200
6/6 - 0s - loss: 450289.5938 - mean_absolute_error: 528.9102 - val_loss: 548193.1250 - val_mean_absolute_error: 534.9274 - 10ms/epoch - 2ms/step
Epoch 22/200
6/6 - 0s - loss: 449808.1875 - mean_absolute_error: 528.7219 - val_loss: 547694.3750 - val_mean_absolute_error: 534.6385 - 10ms/epoch - 2ms/step
Epoch 23/200
6/6 - 0s - loss: 449574.3125 - mean_absolute_error: 528.5306 - val_loss: 547226.1875 - val_mean_absolute_error: 534.3701 - 10ms/epoch - 2ms/step
Epoch 24/200
6/6 - 0s - loss: 448870.4688 - mean_absolute_error: 527.9545 - val_loss: 546722.2500 - val_mean_absolute_error: 534.0815 - 10ms/epoch - 2ms/step
Epoch 25/200
6/6 - 0s - loss: 448453.0312 - mean_absolute_error: 527.7303 - val_loss: 546198.5000 - val_mean_absolute_error: 533.7769 - 10ms/epoch - 2ms/step
Epoch 26/200
6/6 - 0s - loss: 448109.4688 - mean_absolute_error: 527.4079 - val_loss: 545671.1875 - val_mean_absolute_error: 533.4721 - 11ms/epoch - 2ms/step
Epoch 27/200
6/6 - 0s - loss: 447751.2812 - mean_absolute_error: 527.2037 - val_loss: 545126.0000 - val_mean_absolute_error: 533.1661 - 11ms/epoch - 2ms/step
Epoch 28/200
6/6 - 0s - loss: 447469.3125 - mean_absolute_error: 527.0219 - val_loss: 544542.6875 - val_mean_absolute_error: 532.8346 - 10ms/epoch - 2ms/step
Epoch 29/200
6/6 - 0s - loss: 446594.9062 - mean_absolute_error: 526.3979 - val_loss: 543951.1875 - val_mean_absolute_error: 532.4972 - 11ms/epoch - 2ms/step
Epoch 30/200
6/6 - 0s - loss: 446393.7812 - mean_absolute_error: 526.3038 - val_loss: 543334.1875 - val_mean_absolute_error: 532.1483 - 11ms/epoch - 2ms/step
Epoch 31/200
6/6 - 0s - loss: 445739.8125 - mean_absolute_error: 525.7395 - val_loss: 542728.0625 - val_mean_absolute_error: 531.8145 - 10ms/epoch - 2ms/step
Epoch 32/200
6/6 - 0s - loss: 445115.9688 - mean_absolute_error: 525.3983 - val_loss: 542083.8125 - val_mean_absolute_error: 531.4562 - 10ms/epoch - 2ms/step
Epoch 33/200
6/6 - 0s - loss: 444624.0000 - mean_absolute_error: 525.1284 - val_loss: 541434.0000 - val_mean_absolute_error: 531.0928 - 10ms/epoch - 2ms/step
Epoch 34/200
6/6 - 0s - loss: 444433.9062 - mean_absolute_error: 524.8386 - val_loss: 540767.8125 - val_mean_absolute_error: 530.7222 - 10ms/epoch - 2ms/step
Epoch 35/200
6/6 - 0s - loss: 444001.9688 - mean_absolute_error: 524.5123 - val_loss: 540080.2500 - val_mean_absolute_error: 530.3378 - 11ms/epoch - 2ms/step
Epoch 36/200
6/6 - 0s - loss: 443121.3125 - mean_absolute_error: 524.0201 - val_loss: 539371.6250 - val_mean_absolute_error: 529.9501 - 10ms/epoch - 2ms/step
Epoch 37/200
6/6 - 0s - loss: 442096.0000 - mean_absolute_error: 523.4078 - val_loss: 538634.8750 - val_mean_absolute_error: 529.5428 - 10ms/epoch - 2ms/step
Epoch 38/200
6/6 - 0s - loss: 441874.4688 - mean_absolute_error: 523.3515 - val_loss: 537936.4375 - val_mean_absolute_error: 529.1528 - 10ms/epoch - 2ms/step
Epoch 39/200
6/6 - 0s - loss: 441360.2188 - mean_absolute_error: 522.6656 - val_loss: 537237.1250 - val_mean_absolute_error: 528.7619 - 11ms/epoch - 2ms/step
Epoch 40/200
6/6 - 0s - loss: 440366.2812 - mean_absolute_error: 521.9950 - val_loss: 536430.5000 - val_mean_absolute_error: 528.3203 - 10ms/epoch - 2ms/step
Epoch 41/200
6/6 - 0s - loss: 439818.2812 - mean_absolute_error: 522.0264 - val_loss: 535742.3125 - val_mean_absolute_error: 527.9323 - 10ms/epoch - 2ms/step
Epoch 42/200
6/6 - 0s - loss: 439157.3750 - mean_absolute_error: 521.5037 - val_loss: 534991.5000 - val_mean_absolute_error: 527.5181 - 10ms/epoch - 2ms/step
Epoch 43/200
6/6 - 0s - loss: 439753.2188 - mean_absolute_error: 521.6219 - val_loss: 534239.1250 - val_mean_absolute_error: 527.0974 - 10ms/epoch - 2ms/step
Epoch 44/200
6/6 - 0s - loss: 438130.9688 - mean_absolute_error: 520.8491 - val_loss: 533450.6875 - val_mean_absolute_error: 526.6613 - 10ms/epoch - 2ms/step
Epoch 45/200
6/6 - 0s - loss: 437333.1875 - mean_absolute_error: 519.7827 - val_loss: 532590.8750 - val_mean_absolute_error: 526.1923 - 10ms/epoch - 2ms/step
Epoch 46/200
6/6 - 0s - loss: 436990.9062 - mean_absolute_error: 519.9417 - val_loss: 531755.8750 - val_mean_absolute_error: 525.7326 - 10ms/epoch - 2ms/step
Epoch 47/200
6/6 - 0s - loss: 435751.0312 - mean_absolute_error: 518.8458 - val_loss: 530879.1875 - val_mean_absolute_error: 525.2592 - 10ms/epoch - 2ms/step
Epoch 48/200
6/6 - 0s - loss: 435992.9062 - mean_absolute_error: 519.0246 - val_loss: 529997.8125 - val_mean_absolute_error: 524.7847 - 10ms/epoch - 2ms/step
Epoch 49/200
6/6 - 0s - loss: 434710.0312 - mean_absolute_error: 518.0312 - val_loss: 529109.6875 - val_mean_absolute_error: 524.2773 - 11ms/epoch - 2ms/step
Epoch 50/200
6/6 - 0s - loss: 433644.0938 - mean_absolute_error: 517.4256 - val_loss: 528118.5000 - val_mean_absolute_error: 523.7570 - 10ms/epoch - 2ms/step
Epoch 51/200
6/6 - 0s - loss: 432709.4062 - mean_absolute_error: 516.8925 - val_loss: 527212.8750 - val_mean_absolute_error: 523.2562 - 10ms/epoch - 2ms/step
Epoch 52/200
6/6 - 0s - loss: 433644.9688 - mean_absolute_error: 517.1853 - val_loss: 526303.0000 - val_mean_absolute_error: 522.7567 - 10ms/epoch - 2ms/step
Epoch 53/200
6/6 - 0s - loss: 432029.3125 - mean_absolute_error: 516.3247 - val_loss: 525335.9375 - val_mean_absolute_error: 522.2310 - 10ms/epoch - 2ms/step
Epoch 54/200
6/6 - 0s - loss: 430699.8750 - mean_absolute_error: 515.4444 - val_loss: 524356.9375 - val_mean_absolute_error: 521.7037 - 11ms/epoch - 2ms/step
Epoch 55/200
6/6 - 0s - loss: 431111.2188 - mean_absolute_error: 515.2729 - val_loss: 523475.5312 - val_mean_absolute_error: 521.1996 - 66ms/epoch - 11ms/step
Epoch 56/200
6/6 - 0s - loss: 429288.7812 - mean_absolute_error: 514.2086 - val_loss: 522472.9688 - val_mean_absolute_error: 520.6485 - 11ms/epoch - 2ms/step
Epoch 57/200
6/6 - 0s - loss: 428179.4062 - mean_absolute_error: 513.7666 - val_loss: 521370.9062 - val_mean_absolute_error: 520.0483 - 10ms/epoch - 2ms/step
Epoch 58/200
6/6 - 0s - loss: 428181.0312 - mean_absolute_error: 513.3448 - val_loss: 520327.5938 - val_mean_absolute_error: 519.4887 - 10ms/epoch - 2ms/step
Epoch 59/200
6/6 - 0s - loss: 427259.7812 - mean_absolute_error: 512.7341 - val_loss: 519277.5625 - val_mean_absolute_error: 518.9279 - 10ms/epoch - 2ms/step
Epoch 60/200
6/6 - 0s - loss: 425472.2812 - mean_absolute_error: 511.7101 - val_loss: 518155.4375 - val_mean_absolute_error: 518.3114 - 10ms/epoch - 2ms/step
Epoch 61/200
6/6 - 0s - loss: 425853.4062 - mean_absolute_error: 512.0663 - val_loss: 517177.8750 - val_mean_absolute_error: 517.7623 - 10ms/epoch - 2ms/step
Epoch 62/200
6/6 - 0s - loss: 425699.2188 - mean_absolute_error: 511.6192 - val_loss: 515994.4062 - val_mean_absolute_error: 517.1259 - 10ms/epoch - 2ms/step
Epoch 63/200
6/6 - 0s - loss: 422886.7188 - mean_absolute_error: 509.8997 - val_loss: 514905.5938 - val_mean_absolute_error: 516.5106 - 10ms/epoch - 2ms/step
Epoch 64/200
6/6 - 0s - loss: 422742.9062 - mean_absolute_error: 509.6793 - val_loss: 513826.2188 - val_mean_absolute_error: 515.9075 - 10ms/epoch - 2ms/step
Epoch 65/200
6/6 - 0s - loss: 422922.8750 - mean_absolute_error: 509.9855 - val_loss: 512710.7188 - val_mean_absolute_error: 515.2915 - 10ms/epoch - 2ms/step
Epoch 66/200
6/6 - 0s - loss: 420430.0312 - mean_absolute_error: 508.5393 - val_loss: 511477.0625 - val_mean_absolute_error: 514.6227 - 11ms/epoch - 2ms/step
Epoch 67/200
6/6 - 0s - loss: 420432.6250 - mean_absolute_error: 508.0844 - val_loss: 510353.3750 - val_mean_absolute_error: 513.9789 - 10ms/epoch - 2ms/step
Epoch 68/200
6/6 - 0s - loss: 418153.0000 - mean_absolute_error: 506.6998 - val_loss: 509111.3438 - val_mean_absolute_error: 513.2947 - 10ms/epoch - 2ms/step
Epoch 69/200
6/6 - 0s - loss: 418550.9062 - mean_absolute_error: 506.4503 - val_loss: 508002.9062 - val_mean_absolute_error: 512.6650 - 10ms/epoch - 2ms/step
Epoch 70/200
6/6 - 0s - loss: 417282.0938 - mean_absolute_error: 505.6532 - val_loss: 506695.7188 - val_mean_absolute_error: 511.9401 - 10ms/epoch - 2ms/step
Epoch 71/200
6/6 - 0s - loss: 416954.6875 - mean_absolute_error: 505.5904 - val_loss: 505563.3125 - val_mean_absolute_error: 511.3021 - 10ms/epoch - 2ms/step
Epoch 72/200
6/6 - 0s - loss: 415369.5312 - mean_absolute_error: 504.8163 - val_loss: 504353.3750 - val_mean_absolute_error: 510.6243 - 12ms/epoch - 2ms/step
Epoch 73/200
6/6 - 0s - loss: 414303.9062 - mean_absolute_error: 504.0089 - val_loss: 503066.8438 - val_mean_absolute_error: 509.8958 - 11ms/epoch - 2ms/step
Epoch 74/200
6/6 - 0s - loss: 414347.2188 - mean_absolute_error: 503.9976 - val_loss: 501710.9375 - val_mean_absolute_error: 509.1524 - 10ms/epoch - 2ms/step
Epoch 75/200
6/6 - 0s - loss: 413451.8750 - mean_absolute_error: 502.6526 - val_loss: 500507.4375 - val_mean_absolute_error: 508.4712 - 10ms/epoch - 2ms/step
Epoch 76/200
6/6 - 0s - loss: 410112.5312 - mean_absolute_error: 501.1823 - val_loss: 499160.1250 - val_mean_absolute_error: 507.7155 - 10ms/epoch - 2ms/step
Epoch 77/200
6/6 - 0s - loss: 410810.6875 - mean_absolute_error: 501.1636 - val_loss: 497785.8750 - val_mean_absolute_error: 506.9449 - 10ms/epoch - 2ms/step
Epoch 78/200
6/6 - 0s - loss: 409454.0000 - mean_absolute_error: 500.2380 - val_loss: 496484.7500 - val_mean_absolute_error: 506.2052 - 10ms/epoch - 2ms/step
Epoch 79/200
6/6 - 0s - loss: 409367.3125 - mean_absolute_error: 500.2291 - val_loss: 495144.2812 - val_mean_absolute_error: 505.4458 - 10ms/epoch - 2ms/step
Epoch 80/200
6/6 - 0s - loss: 405804.5000 - mean_absolute_error: 497.9783 - val_loss: 493691.2500 - val_mean_absolute_error: 504.6340 - 10ms/epoch - 2ms/step
Epoch 81/200
6/6 - 0s - loss: 405057.3750 - mean_absolute_error: 497.8872 - val_loss: 492291.3125 - val_mean_absolute_error: 503.8467 - 10ms/epoch - 2ms/step
Epoch 82/200
6/6 - 0s - loss: 401948.9688 - mean_absolute_error: 495.4408 - val_loss: 490789.6875 - val_mean_absolute_error: 502.9875 - 10ms/epoch - 2ms/step
Epoch 83/200
6/6 - 0s - loss: 402364.1875 - mean_absolute_error: 495.8929 - val_loss: 489403.0000 - val_mean_absolute_error: 502.2087 - 10ms/epoch - 2ms/step
Epoch 84/200
6/6 - 0s - loss: 401579.6250 - mean_absolute_error: 495.0060 - val_loss: 487877.5312 - val_mean_absolute_error: 501.3492 - 10ms/epoch - 2ms/step
Epoch 85/200
6/6 - 0s - loss: 399423.3750 - mean_absolute_error: 493.0819 - val_loss: 486463.3438 - val_mean_absolute_error: 500.5458 - 10ms/epoch - 2ms/step
Epoch 86/200
6/6 - 0s - loss: 400127.9062 - mean_absolute_error: 493.8124 - val_loss: 484946.8438 - val_mean_absolute_error: 499.6894 - 10ms/epoch - 2ms/step
Epoch 87/200
6/6 - 0s - loss: 397987.1250 - mean_absolute_error: 492.4173 - val_loss: 483436.6875 - val_mean_absolute_error: 498.8308 - 10ms/epoch - 2ms/step
Epoch 88/200
6/6 - 0s - loss: 397863.8750 - mean_absolute_error: 492.5340 - val_loss: 481906.6562 - val_mean_absolute_error: 497.9334 - 10ms/epoch - 2ms/step
Epoch 89/200
6/6 - 0s - loss: 397518.5938 - mean_absolute_error: 490.9420 - val_loss: 480483.1250 - val_mean_absolute_error: 497.0867 - 10ms/epoch - 2ms/step
Epoch 90/200
6/6 - 0s - loss: 394944.3750 - mean_absolute_error: 490.1291 - val_loss: 479043.6875 - val_mean_absolute_error: 496.2483 - 10ms/epoch - 2ms/step
Epoch 91/200
6/6 - 0s - loss: 393093.3125 - mean_absolute_error: 488.8803 - val_loss: 477436.8750 - val_mean_absolute_error: 495.3336 - 10ms/epoch - 2ms/step
Epoch 92/200
6/6 - 0s - loss: 391002.2188 - mean_absolute_error: 487.2285 - val_loss: 475857.4688 - val_mean_absolute_error: 494.4291 - 10ms/epoch - 2ms/step
Epoch 93/200
6/6 - 0s - loss: 391577.4688 - mean_absolute_error: 487.0760 - val_loss: 474245.0000 - val_mean_absolute_error: 493.4959 - 10ms/epoch - 2ms/step
Epoch 94/200
6/6 - 0s - loss: 389428.5938 - mean_absolute_error: 486.3602 - val_loss: 472717.4375 - val_mean_absolute_error: 492.6024 - 10ms/epoch - 2ms/step
Epoch 95/200
6/6 - 0s - loss: 389300.1875 - mean_absolute_error: 484.5935 - val_loss: 471144.9062 - val_mean_absolute_error: 491.6847 - 10ms/epoch - 2ms/step
Epoch 96/200
6/6 - 0s - loss: 387200.5312 - mean_absolute_error: 483.9573 - val_loss: 469507.1250 - val_mean_absolute_error: 490.7230 - 10ms/epoch - 2ms/step
Epoch 97/200
6/6 - 0s - loss: 386776.5000 - mean_absolute_error: 483.7824 - val_loss: 467916.3125 - val_mean_absolute_error: 489.7886 - 10ms/epoch - 2ms/step
Epoch 98/200
6/6 - 0s - loss: 383156.3750 - mean_absolute_error: 482.4832 - val_loss: 466074.6250 - val_mean_absolute_error: 488.7309 - 10ms/epoch - 2ms/step
Epoch 99/200
6/6 - 0s - loss: 385251.9062 - mean_absolute_error: 481.5967 - val_loss: 464511.9688 - val_mean_absolute_error: 487.8041 - 10ms/epoch - 2ms/step
Epoch 100/200
6/6 - 0s - loss: 380765.9688 - mean_absolute_error: 479.6915 - val_loss: 462859.9688 - val_mean_absolute_error: 486.8360 - 10ms/epoch - 2ms/step
Epoch 101/200
6/6 - 0s - loss: 380230.6250 - mean_absolute_error: 479.1034 - val_loss: 461069.9375 - val_mean_absolute_error: 485.7899 - 10ms/epoch - 2ms/step
Epoch 102/200
6/6 - 0s - loss: 377969.0000 - mean_absolute_error: 478.0882 - val_loss: 459270.3438 - val_mean_absolute_error: 484.7251 - 10ms/epoch - 2ms/step
Epoch 103/200
6/6 - 0s - loss: 376617.1562 - mean_absolute_error: 477.2471 - val_loss: 457620.9688 - val_mean_absolute_error: 483.7379 - 10ms/epoch - 2ms/step
Epoch 104/200
6/6 - 0s - loss: 376302.6250 - mean_absolute_error: 476.4473 - val_loss: 455963.9062 - val_mean_absolute_error: 482.7265 - 10ms/epoch - 2ms/step
Epoch 105/200
6/6 - 0s - loss: 375390.9062 - mean_absolute_error: 474.7319 - val_loss: 454323.7812 - val_mean_absolute_error: 481.7216 - 10ms/epoch - 2ms/step
Epoch 106/200
6/6 - 0s - loss: 373833.1562 - mean_absolute_error: 474.5807 - val_loss: 452570.7188 - val_mean_absolute_error: 480.6690 - 10ms/epoch - 2ms/step
Epoch 107/200
6/6 - 0s - loss: 370703.9688 - mean_absolute_error: 471.5928 - val_loss: 450694.6250 - val_mean_absolute_error: 479.5478 - 10ms/epoch - 2ms/step
Epoch 108/200
6/6 - 0s - loss: 369908.5000 - mean_absolute_error: 471.1328 - val_loss: 448933.0625 - val_mean_absolute_error: 478.4801 - 10ms/epoch - 2ms/step
Epoch 109/200
6/6 - 0s - loss: 369410.8125 - mean_absolute_error: 471.6371 - val_loss: 447015.3438 - val_mean_absolute_error: 477.3180 - 10ms/epoch - 2ms/step
Epoch 110/200
6/6 - 0s - loss: 366080.7812 - mean_absolute_error: 466.9518 - val_loss: 445158.7188 - val_mean_absolute_error: 476.2033 - 10ms/epoch - 2ms/step
Epoch 111/200
6/6 - 0s - loss: 366683.8750 - mean_absolute_error: 469.1340 - val_loss: 443338.4375 - val_mean_absolute_error: 475.0867 - 10ms/epoch - 2ms/step
Epoch 112/200
6/6 - 0s - loss: 367389.4375 - mean_absolute_error: 469.6332 - val_loss: 441643.9688 - val_mean_absolute_error: 474.0356 - 10ms/epoch - 2ms/step
Epoch 113/200
6/6 - 0s - loss: 361889.7188 - mean_absolute_error: 465.9209 - val_loss: 439865.5938 - val_mean_absolute_error: 472.9212 - 10ms/epoch - 2ms/step
Epoch 114/200
6/6 - 0s - loss: 364916.5000 - mean_absolute_error: 466.9117 - val_loss: 438112.6875 - val_mean_absolute_error: 471.8118 - 10ms/epoch - 2ms/step
Epoch 115/200
6/6 - 0s - loss: 363479.8438 - mean_absolute_error: 465.4924 - val_loss: 436241.8438 - val_mean_absolute_error: 470.6565 - 10ms/epoch - 2ms/step
Epoch 116/200
6/6 - 0s - loss: 358667.1875 - mean_absolute_error: 462.5723 - val_loss: 434346.9062 - val_mean_absolute_error: 469.4933 - 10ms/epoch - 2ms/step
Epoch 117/200
6/6 - 0s - loss: 355970.5312 - mean_absolute_error: 460.9546 - val_loss: 432481.0625 - val_mean_absolute_error: 468.3506 - 10ms/epoch - 2ms/step
Epoch 118/200
6/6 - 0s - loss: 359861.0312 - mean_absolute_error: 462.6089 - val_loss: 430634.6562 - val_mean_absolute_error: 467.2239 - 10ms/epoch - 2ms/step
Epoch 119/200
6/6 - 0s - loss: 357905.3438 - mean_absolute_error: 461.8838 - val_loss: 428731.7188 - val_mean_absolute_error: 466.0367 - 10ms/epoch - 2ms/step
Epoch 120/200
6/6 - 0s - loss: 354499.6875 - mean_absolute_error: 457.0815 - val_loss: 426774.0312 - val_mean_absolute_error: 464.8149 - 10ms/epoch - 2ms/step
Epoch 121/200
6/6 - 0s - loss: 349615.0312 - mean_absolute_error: 456.9603 - val_loss: 424805.2500 - val_mean_absolute_error: 463.5633 - 10ms/epoch - 2ms/step
Epoch 122/200
6/6 - 0s - loss: 353988.7812 - mean_absolute_error: 458.3514 - val_loss: 422945.6562 - val_mean_absolute_error: 462.4018 - 10ms/epoch - 2ms/step
Epoch 123/200
6/6 - 0s - loss: 350323.1250 - mean_absolute_error: 456.8160 - val_loss: 421147.2500 - val_mean_absolute_error: 461.2064 - 10ms/epoch - 2ms/step
Epoch 124/200
6/6 - 0s - loss: 351992.3750 - mean_absolute_error: 457.6591 - val_loss: 419206.9375 - val_mean_absolute_error: 459.9932 - 10ms/epoch - 2ms/step
Epoch 125/200
6/6 - 0s - loss: 347396.4062 - mean_absolute_error: 454.4008 - val_loss: 417297.0938 - val_mean_absolute_error: 458.7978 - 10ms/epoch - 2ms/step
Epoch 126/200
6/6 - 0s - loss: 344115.6875 - mean_absolute_error: 450.9437 - val_loss: 415294.5625 - val_mean_absolute_error: 457.5463 - 10ms/epoch - 2ms/step
Epoch 127/200
6/6 - 0s - loss: 341962.1875 - mean_absolute_error: 451.2536 - val_loss: 413440.5000 - val_mean_absolute_error: 456.3299 - 10ms/epoch - 2ms/step
Epoch 128/200
6/6 - 0s - loss: 342221.9688 - mean_absolute_error: 449.8386 - val_loss: 411421.1562 - val_mean_absolute_error: 455.0374 - 10ms/epoch - 2ms/step
Epoch 129/200
6/6 - 0s - loss: 340962.9375 - mean_absolute_error: 447.3974 - val_loss: 409340.5000 - val_mean_absolute_error: 453.6942 - 10ms/epoch - 2ms/step
Epoch 130/200
6/6 - 0s - loss: 338054.8750 - mean_absolute_error: 445.8729 - val_loss: 407387.2188 - val_mean_absolute_error: 452.4137 - 10ms/epoch - 2ms/step
Epoch 131/200
6/6 - 0s - loss: 337054.2812 - mean_absolute_error: 446.5490 - val_loss: 405457.1562 - val_mean_absolute_error: 451.1322 - 11ms/epoch - 2ms/step
Epoch 132/200
6/6 - 0s - loss: 334021.1875 - mean_absolute_error: 443.1089 - val_loss: 403339.0000 - val_mean_absolute_error: 449.7456 - 10ms/epoch - 2ms/step
Epoch 133/200
6/6 - 0s - loss: 333507.4688 - mean_absolute_error: 442.9330 - val_loss: 401198.9062 - val_mean_absolute_error: 448.3734 - 10ms/epoch - 2ms/step
Epoch 134/200
6/6 - 0s - loss: 331746.7188 - mean_absolute_error: 440.3589 - val_loss: 399055.6875 - val_mean_absolute_error: 446.9790 - 10ms/epoch - 2ms/step
Epoch 135/200
6/6 - 0s - loss: 330880.6250 - mean_absolute_error: 442.0336 - val_loss: 397153.2812 - val_mean_absolute_error: 445.7281 - 10ms/epoch - 2ms/step
Epoch 136/200
6/6 - 0s - loss: 328615.2188 - mean_absolute_error: 438.7973 - val_loss: 395241.8438 - val_mean_absolute_error: 444.4423 - 10ms/epoch - 2ms/step
Epoch 137/200
6/6 - 0s - loss: 330739.0625 - mean_absolute_error: 439.2924 - val_loss: 393131.0000 - val_mean_absolute_error: 443.0517 - 10ms/epoch - 2ms/step
Epoch 138/200
6/6 - 0s - loss: 325763.2188 - mean_absolute_error: 437.0589 - val_loss: 391121.7500 - val_mean_absolute_error: 441.6981 - 10ms/epoch - 2ms/step
Epoch 139/200
6/6 - 0s - loss: 323558.8750 - mean_absolute_error: 434.4060 - val_loss: 389071.7812 - val_mean_absolute_error: 440.3284 - 11ms/epoch - 2ms/step
Epoch 140/200
6/6 - 0s - loss: 322850.0625 - mean_absolute_error: 435.2313 - val_loss: 386877.5625 - val_mean_absolute_error: 438.8844 - 10ms/epoch - 2ms/step
Epoch 141/200
6/6 - 0s - loss: 331660.4062 - mean_absolute_error: 438.6490 - val_loss: 384866.5312 - val_mean_absolute_error: 437.5268 - 10ms/epoch - 2ms/step
Epoch 142/200
6/6 - 0s - loss: 320687.3750 - mean_absolute_error: 430.8550 - val_loss: 382805.0312 - val_mean_absolute_error: 436.1392 - 10ms/epoch - 2ms/step
Epoch 143/200
6/6 - 0s - loss: 321845.6875 - mean_absolute_error: 430.7142 - val_loss: 380839.7188 - val_mean_absolute_error: 434.8146 - 10ms/epoch - 2ms/step
Epoch 144/200
6/6 - 0s - loss: 317307.6562 - mean_absolute_error: 428.9474 - val_loss: 378701.6562 - val_mean_absolute_error: 433.5190 - 10ms/epoch - 2ms/step
Epoch 145/200
6/6 - 0s - loss: 315723.5938 - mean_absolute_error: 429.2912 - val_loss: 376502.6562 - val_mean_absolute_error: 432.1972 - 10ms/epoch - 2ms/step
Epoch 146/200
6/6 - 0s - loss: 316795.0000 - mean_absolute_error: 428.6329 - val_loss: 374747.1250 - val_mean_absolute_error: 431.0963 - 10ms/epoch - 2ms/step
Epoch 147/200
6/6 - 0s - loss: 314484.5938 - mean_absolute_error: 429.2571 - val_loss: 372673.0000 - val_mean_absolute_error: 429.8430 - 10ms/epoch - 2ms/step
Epoch 148/200
6/6 - 0s - loss: 308927.8438 - mean_absolute_error: 422.7982 - val_loss: 370628.8750 - val_mean_absolute_error: 428.6008 - 10ms/epoch - 2ms/step
Epoch 149/200
6/6 - 0s - loss: 311078.5312 - mean_absolute_error: 423.0562 - val_loss: 368694.2500 - val_mean_absolute_error: 427.4211 - 10ms/epoch - 2ms/step
Epoch 150/200
6/6 - 0s - loss: 310208.1250 - mean_absolute_error: 423.3729 - val_loss: 366528.8125 - val_mean_absolute_error: 426.0743 - 10ms/epoch - 2ms/step
Epoch 151/200
6/6 - 0s - loss: 311562.6250 - mean_absolute_error: 426.3978 - val_loss: 364298.1875 - val_mean_absolute_error: 424.6875 - 10ms/epoch - 2ms/step
Epoch 152/200
6/6 - 0s - loss: 303472.3750 - mean_absolute_error: 420.0942 - val_loss: 362365.6875 - val_mean_absolute_error: 423.4401 - 10ms/epoch - 2ms/step
Epoch 153/200
6/6 - 0s - loss: 303378.1250 - mean_absolute_error: 419.0874 - val_loss: 360231.6250 - val_mean_absolute_error: 422.0830 - 10ms/epoch - 2ms/step
Epoch 154/200
6/6 - 0s - loss: 295600.5312 - mean_absolute_error: 412.5335 - val_loss: 358068.1250 - val_mean_absolute_error: 420.7325 - 10ms/epoch - 2ms/step
Epoch 155/200
6/6 - 0s - loss: 298041.6250 - mean_absolute_error: 416.2326 - val_loss: 355893.8438 - val_mean_absolute_error: 419.3469 - 10ms/epoch - 2ms/step
Epoch 156/200
6/6 - 0s - loss: 303423.5938 - mean_absolute_error: 415.8309 - val_loss: 353870.9062 - val_mean_absolute_error: 418.0575 - 10ms/epoch - 2ms/step
Epoch 157/200
6/6 - 0s - loss: 303022.6875 - mean_absolute_error: 414.9170 - val_loss: 351780.4688 - val_mean_absolute_error: 416.6928 - 11ms/epoch - 2ms/step
Epoch 158/200
6/6 - 0s - loss: 300935.9062 - mean_absolute_error: 416.6302 - val_loss: 349667.1875 - val_mean_absolute_error: 415.3460 - 10ms/epoch - 2ms/step
Epoch 159/200
6/6 - 0s - loss: 292214.9375 - mean_absolute_error: 407.6065 - val_loss: 347392.6875 - val_mean_absolute_error: 413.8969 - 10ms/epoch - 2ms/step
Epoch 160/200
6/6 - 0s - loss: 289801.5938 - mean_absolute_error: 406.9357 - val_loss: 345411.3438 - val_mean_absolute_error: 412.5738 - 10ms/epoch - 2ms/step
Epoch 161/200
6/6 - 0s - loss: 289965.8750 - mean_absolute_error: 408.0152 - val_loss: 343261.7188 - val_mean_absolute_error: 411.1647 - 10ms/epoch - 2ms/step
Epoch 162/200
6/6 - 0s - loss: 289831.4688 - mean_absolute_error: 404.7542 - val_loss: 341169.6875 - val_mean_absolute_error: 409.7838 - 10ms/epoch - 2ms/step
Epoch 163/200
6/6 - 0s - loss: 286189.9375 - mean_absolute_error: 403.0818 - val_loss: 339027.8125 - val_mean_absolute_error: 408.3550 - 10ms/epoch - 2ms/step
Epoch 164/200
6/6 - 0s - loss: 282664.2812 - mean_absolute_error: 400.5613 - val_loss: 336970.8125 - val_mean_absolute_error: 406.9870 - 10ms/epoch - 2ms/step
Epoch 165/200
6/6 - 0s - loss: 283466.5938 - mean_absolute_error: 400.7331 - val_loss: 334638.0938 - val_mean_absolute_error: 405.4840 - 10ms/epoch - 2ms/step
Epoch 166/200
6/6 - 0s - loss: 280598.6562 - mean_absolute_error: 401.0731 - val_loss: 332565.9062 - val_mean_absolute_error: 404.0999 - 10ms/epoch - 2ms/step
Epoch 167/200
6/6 - 0s - loss: 283739.8750 - mean_absolute_error: 398.2195 - val_loss: 330616.5000 - val_mean_absolute_error: 402.7610 - 10ms/epoch - 2ms/step
Epoch 168/200
6/6 - 0s - loss: 274558.0625 - mean_absolute_error: 398.1595 - val_loss: 328592.2812 - val_mean_absolute_error: 401.4059 - 10ms/epoch - 2ms/step
Epoch 169/200
6/6 - 0s - loss: 276763.7812 - mean_absolute_error: 396.3059 - val_loss: 326475.2500 - val_mean_absolute_error: 399.9701 - 10ms/epoch - 2ms/step
Epoch 170/200
6/6 - 0s - loss: 278701.0000 - mean_absolute_error: 395.9399 - val_loss: 324272.0312 - val_mean_absolute_error: 398.5253 - 10ms/epoch - 2ms/step
Epoch 171/200
6/6 - 0s - loss: 282500.7188 - mean_absolute_error: 397.6640 - val_loss: 322271.0312 - val_mean_absolute_error: 397.1667 - 10ms/epoch - 2ms/step
Epoch 172/200
6/6 - 0s - loss: 273657.7188 - mean_absolute_error: 394.5903 - val_loss: 320086.5625 - val_mean_absolute_error: 395.7038 - 10ms/epoch - 2ms/step
Epoch 173/200
6/6 - 0s - loss: 267476.1875 - mean_absolute_error: 388.2028 - val_loss: 317879.5000 - val_mean_absolute_error: 394.2269 - 10ms/epoch - 2ms/step
Epoch 174/200
6/6 - 0s - loss: 270765.0625 - mean_absolute_error: 389.0839 - val_loss: 315971.8125 - val_mean_absolute_error: 392.9113 - 10ms/epoch - 2ms/step
Epoch 175/200
6/6 - 0s - loss: 269197.9688 - mean_absolute_error: 391.3350 - val_loss: 314067.3750 - val_mean_absolute_error: 391.6120 - 10ms/epoch - 2ms/step
Epoch 176/200
6/6 - 0s - loss: 265883.6250 - mean_absolute_error: 383.4491 - val_loss: 312019.1875 - val_mean_absolute_error: 390.2160 - 10ms/epoch - 2ms/step
Epoch 177/200
6/6 - 0s - loss: 264999.0000 - mean_absolute_error: 386.0545 - val_loss: 310034.1250 - val_mean_absolute_error: 388.8433 - 10ms/epoch - 2ms/step
Epoch 178/200
6/6 - 0s - loss: 263771.2500 - mean_absolute_error: 383.6074 - val_loss: 307954.9375 - val_mean_absolute_error: 387.4091 - 10ms/epoch - 2ms/step
Epoch 179/200
6/6 - 0s - loss: 258677.9531 - mean_absolute_error: 380.1298 - val_loss: 305798.2188 - val_mean_absolute_error: 385.9161 - 31ms/epoch - 5ms/step
Epoch 180/200
6/6 - 0s - loss: 257289.0156 - mean_absolute_error: 381.7982 - val_loss: 303675.3125 - val_mean_absolute_error: 384.4444 - 10ms/epoch - 2ms/step
Epoch 181/200
6/6 - 0s - loss: 260678.8594 - mean_absolute_error: 381.0237 - val_loss: 301632.4062 - val_mean_absolute_error: 383.0453 - 10ms/epoch - 2ms/step
Epoch 182/200
6/6 - 0s - loss: 261821.2656 - mean_absolute_error: 377.9318 - val_loss: 299677.8125 - val_mean_absolute_error: 381.6693 - 10ms/epoch - 2ms/step
Epoch 183/200
6/6 - 0s - loss: 256818.4375 - mean_absolute_error: 378.9872 - val_loss: 297573.1562 - val_mean_absolute_error: 380.2743 - 10ms/epoch - 2ms/step
Epoch 184/200
6/6 - 0s - loss: 256691.5000 - mean_absolute_error: 376.1594 - val_loss: 295526.1250 - val_mean_absolute_error: 378.9202 - 10ms/epoch - 2ms/step
Epoch 185/200
6/6 - 0s - loss: 251718.1406 - mean_absolute_error: 371.9655 - val_loss: 293482.1250 - val_mean_absolute_error: 377.5916 - 10ms/epoch - 2ms/step
Epoch 186/200
6/6 - 0s - loss: 254457.0625 - mean_absolute_error: 372.8750 - val_loss: 291525.5312 - val_mean_absolute_error: 376.2619 - 10ms/epoch - 2ms/step
Epoch 187/200
6/6 - 0s - loss: 254303.1094 - mean_absolute_error: 375.0532 - val_loss: 289547.8125 - val_mean_absolute_error: 374.9360 - 10ms/epoch - 2ms/step
Epoch 188/200
6/6 - 0s - loss: 249398.0469 - mean_absolute_error: 367.4701 - val_loss: 287529.6562 - val_mean_absolute_error: 373.5989 - 10ms/epoch - 2ms/step
Epoch 189/200
6/6 - 0s - loss: 251846.1406 - mean_absolute_error: 372.3690 - val_loss: 285564.1250 - val_mean_absolute_error: 372.2686 - 10ms/epoch - 2ms/step
Epoch 190/200
6/6 - 0s - loss: 246037.9531 - mean_absolute_error: 367.3746 - val_loss: 283596.3125 - val_mean_absolute_error: 370.9166 - 10ms/epoch - 2ms/step
Epoch 191/200
6/6 - 0s - loss: 239413.0938 - mean_absolute_error: 363.8889 - val_loss: 281436.4375 - val_mean_absolute_error: 369.4369 - 10ms/epoch - 2ms/step
Epoch 192/200
6/6 - 0s - loss: 246557.5938 - mean_absolute_error: 366.4144 - val_loss: 279443.5312 - val_mean_absolute_error: 368.0439 - 10ms/epoch - 2ms/step
Epoch 193/200
6/6 - 0s - loss: 248010.8125 - mean_absolute_error: 370.2404 - val_loss: 277384.1250 - val_mean_absolute_error: 366.6595 - 10ms/epoch - 2ms/step
Epoch 194/200
6/6 - 0s - loss: 241252.1406 - mean_absolute_error: 363.7589 - val_loss: 275391.0938 - val_mean_absolute_error: 365.3293 - 10ms/epoch - 2ms/step
Epoch 195/200
6/6 - 0s - loss: 238527.2031 - mean_absolute_error: 360.7314 - val_loss: 273509.9375 - val_mean_absolute_error: 364.0348 - 10ms/epoch - 2ms/step
Epoch 196/200
6/6 - 0s - loss: 234680.8906 - mean_absolute_error: 353.2372 - val_loss: 271691.9688 - val_mean_absolute_error: 362.7867 - 10ms/epoch - 2ms/step
Epoch 197/200
6/6 - 0s - loss: 237003.8594 - mean_absolute_error: 359.5112 - val_loss: 269841.7500 - val_mean_absolute_error: 361.5223 - 10ms/epoch - 2ms/step
Epoch 198/200
6/6 - 0s - loss: 234107.4844 - mean_absolute_error: 355.6237 - val_loss: 267764.8750 - val_mean_absolute_error: 360.1449 - 10ms/epoch - 2ms/step
Epoch 199/200
6/6 - 0s - loss: 234114.3438 - mean_absolute_error: 358.5441 - val_loss: 265918.2188 - val_mean_absolute_error: 358.8826 - 10ms/epoch - 2ms/step
Epoch 200/200
6/6 - 0s - loss: 224866.4375 - mean_absolute_error: 348.2207 - val_loss: 263942.3125 - val_mean_absolute_error: 357.5414 - 10ms/epoch - 2ms/step</code></pre>
</div>
</div>
<p>Keras reports for each epoch the value of the loss metric (mean squared error) for the training and validation data and the monitored metrics (mean absolute error) for the validation data. As you can see from the lengthy output, all criteria are still decreasing after 200 epochs. It is helpful to view the epoch history graphically. If you run the code in an interactive environment (e.g., RStudio), the epoch history is displayed and updated live. You can always plot the epoch <code>history</code> with the <code>plot</code> command:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(history, <span class="at">smooth=</span><span class="cn">FALSE</span>)  <span class="co"># see ?plot.keras_training_history for doc</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-hitters-ann-200" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hitters-ann-200-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="ann_R_files/figure-html/fig-hitters-ann-200-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="quarto-lightbox-gallery-1"><img src="ann_R_files/figure-html/fig-hitters-ann-200-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hitters-ann-200-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.1: Epoch history for the first 200 epochs.
</figcaption>
</figure>
</div>
</div>
</div>
<p>All criteria are steadily declining and have not leveled out after 200 epochs (<a href="#fig-hitters-ann-200" class="quarto-xref">Figure&nbsp;<span>33.1</span></a>). As expected, the mean squared error and mean absolute error are higher in the validation data than in the training data. This is not always the case when training neural networks. Maybe surprisingly, after about 75 epochs the metrics are showing more ariability from epoch to epoch in the training data than in the validation data. Also, there is no guarantee that criteria decrease monotonically, the mean squared error of epoch <span class="math inline">\(t\)</span> can be higher than that of epoch <span class="math inline">\(t-1\)</span>. We are looking for the results to settle down and stabilize before calling the optimization completed. More epochs need to be run in this example. Fortunately, you can continue where the previous run has left off. The following code trains the network for another 100 epochs:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>firstANN <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(x[<span class="sc">-</span>testid, ], </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        y[<span class="sc">-</span>testid], </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">epochs=</span><span class="dv">100</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">batch_size=</span><span class="dv">32</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">validation_data=</span> <span class="fu">list</span>(x[testid, ], y[testid])</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/100
6/6 - 0s - loss: 230825.5938 - mean_absolute_error: 355.6971 - val_loss: 262156.6562 - val_mean_absolute_error: 356.3004 - 29ms/epoch - 5ms/step
Epoch 2/100
6/6 - 0s - loss: 232892.9531 - mean_absolute_error: 354.3773 - val_loss: 260309.8438 - val_mean_absolute_error: 355.0233 - 11ms/epoch - 2ms/step
Epoch 3/100
6/6 - 0s - loss: 231815.1562 - mean_absolute_error: 351.4536 - val_loss: 258375.1719 - val_mean_absolute_error: 353.7148 - 11ms/epoch - 2ms/step
Epoch 4/100
6/6 - 0s - loss: 223649.4062 - mean_absolute_error: 345.0608 - val_loss: 256549.4062 - val_mean_absolute_error: 352.4305 - 11ms/epoch - 2ms/step
Epoch 5/100
6/6 - 0s - loss: 223402.5625 - mean_absolute_error: 347.3586 - val_loss: 254846.2031 - val_mean_absolute_error: 351.1815 - 11ms/epoch - 2ms/step
Epoch 6/100
6/6 - 0s - loss: 231514.5938 - mean_absolute_error: 354.5130 - val_loss: 253017.1094 - val_mean_absolute_error: 349.9748 - 11ms/epoch - 2ms/step
Epoch 7/100
6/6 - 0s - loss: 230839.7656 - mean_absolute_error: 353.8985 - val_loss: 251431.1250 - val_mean_absolute_error: 348.9644 - 11ms/epoch - 2ms/step
Epoch 8/100
6/6 - 0s - loss: 219182.9844 - mean_absolute_error: 342.2823 - val_loss: 249603.8594 - val_mean_absolute_error: 347.7954 - 11ms/epoch - 2ms/step
Epoch 9/100
6/6 - 0s - loss: 223333.8594 - mean_absolute_error: 343.7765 - val_loss: 247663.5938 - val_mean_absolute_error: 346.5789 - 11ms/epoch - 2ms/step
Epoch 10/100
6/6 - 0s - loss: 223022.5938 - mean_absolute_error: 347.2039 - val_loss: 246067.2812 - val_mean_absolute_error: 345.5313 - 10ms/epoch - 2ms/step
Epoch 11/100
6/6 - 0s - loss: 221038.7344 - mean_absolute_error: 346.6453 - val_loss: 244397.3750 - val_mean_absolute_error: 344.4289 - 11ms/epoch - 2ms/step
Epoch 12/100
6/6 - 0s - loss: 218228.5469 - mean_absolute_error: 343.2308 - val_loss: 242870.6406 - val_mean_absolute_error: 343.4254 - 11ms/epoch - 2ms/step
Epoch 13/100
6/6 - 0s - loss: 217654.0625 - mean_absolute_error: 343.6697 - val_loss: 241093.6094 - val_mean_absolute_error: 342.2592 - 10ms/epoch - 2ms/step
Epoch 14/100
6/6 - 0s - loss: 208377.5156 - mean_absolute_error: 338.1669 - val_loss: 239320.5312 - val_mean_absolute_error: 341.1316 - 10ms/epoch - 2ms/step
Epoch 15/100
6/6 - 0s - loss: 220586.7031 - mean_absolute_error: 345.0900 - val_loss: 237887.8125 - val_mean_absolute_error: 340.1930 - 10ms/epoch - 2ms/step
Epoch 16/100
6/6 - 0s - loss: 212606.1562 - mean_absolute_error: 336.3293 - val_loss: 236457.5000 - val_mean_absolute_error: 339.2629 - 10ms/epoch - 2ms/step
Epoch 17/100
6/6 - 0s - loss: 213167.8906 - mean_absolute_error: 336.9067 - val_loss: 234860.0469 - val_mean_absolute_error: 338.2314 - 10ms/epoch - 2ms/step
Epoch 18/100
6/6 - 0s - loss: 211055.1875 - mean_absolute_error: 333.8047 - val_loss: 233477.5000 - val_mean_absolute_error: 337.3269 - 10ms/epoch - 2ms/step
Epoch 19/100
6/6 - 0s - loss: 206592.9375 - mean_absolute_error: 332.9531 - val_loss: 231747.8594 - val_mean_absolute_error: 336.2451 - 10ms/epoch - 2ms/step
Epoch 20/100
6/6 - 0s - loss: 209797.2500 - mean_absolute_error: 336.2022 - val_loss: 230028.9219 - val_mean_absolute_error: 335.1982 - 10ms/epoch - 2ms/step
Epoch 21/100
6/6 - 0s - loss: 205915.9844 - mean_absolute_error: 331.3284 - val_loss: 228604.6719 - val_mean_absolute_error: 334.3110 - 10ms/epoch - 2ms/step
Epoch 22/100
6/6 - 0s - loss: 204092.7344 - mean_absolute_error: 331.6947 - val_loss: 227183.6562 - val_mean_absolute_error: 333.4285 - 10ms/epoch - 2ms/step
Epoch 23/100
6/6 - 0s - loss: 207432.8438 - mean_absolute_error: 334.3043 - val_loss: 225913.0156 - val_mean_absolute_error: 332.6386 - 10ms/epoch - 2ms/step
Epoch 24/100
6/6 - 0s - loss: 210640.6094 - mean_absolute_error: 336.5605 - val_loss: 224445.5156 - val_mean_absolute_error: 331.8502 - 10ms/epoch - 2ms/step
Epoch 25/100
6/6 - 0s - loss: 205105.2656 - mean_absolute_error: 331.6780 - val_loss: 222901.6562 - val_mean_absolute_error: 331.0226 - 10ms/epoch - 2ms/step
Epoch 26/100
6/6 - 0s - loss: 212548.8125 - mean_absolute_error: 333.5360 - val_loss: 221409.5938 - val_mean_absolute_error: 330.2072 - 10ms/epoch - 2ms/step
Epoch 27/100
6/6 - 0s - loss: 201731.5625 - mean_absolute_error: 327.3340 - val_loss: 219751.5625 - val_mean_absolute_error: 329.3179 - 10ms/epoch - 2ms/step
Epoch 28/100
6/6 - 0s - loss: 210256.1562 - mean_absolute_error: 329.2336 - val_loss: 218536.7344 - val_mean_absolute_error: 328.6278 - 10ms/epoch - 2ms/step
Epoch 29/100
6/6 - 0s - loss: 201465.1094 - mean_absolute_error: 330.5270 - val_loss: 217130.7969 - val_mean_absolute_error: 327.8409 - 10ms/epoch - 2ms/step
Epoch 30/100
6/6 - 0s - loss: 199210.4062 - mean_absolute_error: 325.3864 - val_loss: 215704.1406 - val_mean_absolute_error: 327.0403 - 10ms/epoch - 2ms/step
Epoch 31/100
6/6 - 0s - loss: 201590.1562 - mean_absolute_error: 330.3507 - val_loss: 214417.4219 - val_mean_absolute_error: 326.3163 - 10ms/epoch - 2ms/step
Epoch 32/100
6/6 - 0s - loss: 200551.8594 - mean_absolute_error: 330.0930 - val_loss: 213133.4531 - val_mean_absolute_error: 325.5972 - 10ms/epoch - 2ms/step
Epoch 33/100
6/6 - 0s - loss: 192603.3438 - mean_absolute_error: 318.3838 - val_loss: 211659.3281 - val_mean_absolute_error: 324.7675 - 10ms/epoch - 2ms/step
Epoch 34/100
6/6 - 0s - loss: 191093.2656 - mean_absolute_error: 316.9084 - val_loss: 210439.3594 - val_mean_absolute_error: 324.0537 - 10ms/epoch - 2ms/step
Epoch 35/100
6/6 - 0s - loss: 191296.4375 - mean_absolute_error: 320.3608 - val_loss: 208988.7188 - val_mean_absolute_error: 323.2534 - 10ms/epoch - 2ms/step
Epoch 36/100
6/6 - 0s - loss: 192979.5156 - mean_absolute_error: 317.3400 - val_loss: 207589.0625 - val_mean_absolute_error: 322.4818 - 10ms/epoch - 2ms/step
Epoch 37/100
6/6 - 0s - loss: 201639.6875 - mean_absolute_error: 327.2420 - val_loss: 206446.0938 - val_mean_absolute_error: 321.8338 - 10ms/epoch - 2ms/step
Epoch 38/100
6/6 - 0s - loss: 200510.8906 - mean_absolute_error: 324.4880 - val_loss: 205281.1250 - val_mean_absolute_error: 321.1718 - 10ms/epoch - 2ms/step
Epoch 39/100
6/6 - 0s - loss: 185054.1094 - mean_absolute_error: 315.0226 - val_loss: 203744.9844 - val_mean_absolute_error: 320.2894 - 10ms/epoch - 2ms/step
Epoch 40/100
6/6 - 0s - loss: 193375.4375 - mean_absolute_error: 323.6259 - val_loss: 202319.0781 - val_mean_absolute_error: 319.4901 - 10ms/epoch - 2ms/step
Epoch 41/100
6/6 - 0s - loss: 188250.1406 - mean_absolute_error: 318.5400 - val_loss: 201015.7031 - val_mean_absolute_error: 318.7601 - 10ms/epoch - 2ms/step
Epoch 42/100
6/6 - 0s - loss: 193489.6094 - mean_absolute_error: 317.5714 - val_loss: 199722.6406 - val_mean_absolute_error: 318.0356 - 10ms/epoch - 2ms/step
Epoch 43/100
6/6 - 0s - loss: 189827.1562 - mean_absolute_error: 316.9716 - val_loss: 198523.8906 - val_mean_absolute_error: 317.3316 - 10ms/epoch - 2ms/step
Epoch 44/100
6/6 - 0s - loss: 181224.0156 - mean_absolute_error: 311.2296 - val_loss: 197257.7188 - val_mean_absolute_error: 316.5898 - 10ms/epoch - 2ms/step
Epoch 45/100
6/6 - 0s - loss: 179183.5469 - mean_absolute_error: 308.4769 - val_loss: 195822.7188 - val_mean_absolute_error: 315.7467 - 10ms/epoch - 2ms/step
Epoch 46/100
6/6 - 0s - loss: 190135.9375 - mean_absolute_error: 315.9671 - val_loss: 194641.6562 - val_mean_absolute_error: 315.0476 - 10ms/epoch - 2ms/step
Epoch 47/100
6/6 - 0s - loss: 186391.5156 - mean_absolute_error: 318.7709 - val_loss: 193577.6562 - val_mean_absolute_error: 314.4093 - 10ms/epoch - 2ms/step
Epoch 48/100
6/6 - 0s - loss: 182514.2656 - mean_absolute_error: 308.9046 - val_loss: 192363.8906 - val_mean_absolute_error: 313.6801 - 10ms/epoch - 2ms/step
Epoch 49/100
6/6 - 0s - loss: 187011.5156 - mean_absolute_error: 314.1225 - val_loss: 191371.0156 - val_mean_absolute_error: 313.0635 - 10ms/epoch - 2ms/step
Epoch 50/100
6/6 - 0s - loss: 185364.2344 - mean_absolute_error: 314.0539 - val_loss: 190250.0469 - val_mean_absolute_error: 312.3679 - 10ms/epoch - 2ms/step
Epoch 51/100
6/6 - 0s - loss: 188798.0469 - mean_absolute_error: 313.4819 - val_loss: 189317.0781 - val_mean_absolute_error: 311.7888 - 10ms/epoch - 2ms/step
Epoch 52/100
6/6 - 0s - loss: 181541.7188 - mean_absolute_error: 309.0490 - val_loss: 188250.4375 - val_mean_absolute_error: 311.1123 - 10ms/epoch - 2ms/step
Epoch 53/100
6/6 - 0s - loss: 183282.5000 - mean_absolute_error: 312.4948 - val_loss: 187106.2344 - val_mean_absolute_error: 310.3903 - 10ms/epoch - 2ms/step
Epoch 54/100
6/6 - 0s - loss: 177001.0625 - mean_absolute_error: 307.9321 - val_loss: 185992.1875 - val_mean_absolute_error: 309.6841 - 10ms/epoch - 2ms/step
Epoch 55/100
6/6 - 0s - loss: 181172.3750 - mean_absolute_error: 310.1151 - val_loss: 185058.4375 - val_mean_absolute_error: 309.0712 - 10ms/epoch - 2ms/step
Epoch 56/100
6/6 - 0s - loss: 187237.4844 - mean_absolute_error: 314.1746 - val_loss: 184281.0156 - val_mean_absolute_error: 308.5687 - 10ms/epoch - 2ms/step
Epoch 57/100
6/6 - 0s - loss: 188233.4531 - mean_absolute_error: 318.4173 - val_loss: 183423.5938 - val_mean_absolute_error: 307.9957 - 10ms/epoch - 2ms/step
Epoch 58/100
6/6 - 0s - loss: 170369.5156 - mean_absolute_error: 301.2923 - val_loss: 182289.1875 - val_mean_absolute_error: 307.2569 - 10ms/epoch - 2ms/step
Epoch 59/100
6/6 - 0s - loss: 177835.6250 - mean_absolute_error: 303.1884 - val_loss: 181354.8594 - val_mean_absolute_error: 306.6402 - 10ms/epoch - 2ms/step
Epoch 60/100
6/6 - 0s - loss: 185815.2344 - mean_absolute_error: 314.1513 - val_loss: 180443.6250 - val_mean_absolute_error: 306.0244 - 10ms/epoch - 2ms/step
Epoch 61/100
6/6 - 0s - loss: 178955.8906 - mean_absolute_error: 307.7710 - val_loss: 179756.9688 - val_mean_absolute_error: 305.5555 - 10ms/epoch - 2ms/step
Epoch 62/100
6/6 - 0s - loss: 173391.7344 - mean_absolute_error: 305.7234 - val_loss: 178755.7500 - val_mean_absolute_error: 304.8942 - 10ms/epoch - 2ms/step
Epoch 63/100
6/6 - 0s - loss: 177317.2812 - mean_absolute_error: 307.6441 - val_loss: 177997.7969 - val_mean_absolute_error: 304.3836 - 10ms/epoch - 2ms/step
Epoch 64/100
6/6 - 0s - loss: 181512.5625 - mean_absolute_error: 311.0006 - val_loss: 177306.6875 - val_mean_absolute_error: 303.9125 - 10ms/epoch - 2ms/step
Epoch 65/100
6/6 - 0s - loss: 178662.8125 - mean_absolute_error: 312.7106 - val_loss: 176424.4062 - val_mean_absolute_error: 303.3031 - 10ms/epoch - 2ms/step
Epoch 66/100
6/6 - 0s - loss: 164362.1875 - mean_absolute_error: 300.6029 - val_loss: 175446.6406 - val_mean_absolute_error: 302.6243 - 10ms/epoch - 2ms/step
Epoch 67/100
6/6 - 0s - loss: 171215.5000 - mean_absolute_error: 299.7152 - val_loss: 174610.1094 - val_mean_absolute_error: 302.0517 - 10ms/epoch - 2ms/step
Epoch 68/100
6/6 - 0s - loss: 180577.7500 - mean_absolute_error: 305.5556 - val_loss: 173782.7656 - val_mean_absolute_error: 301.4666 - 10ms/epoch - 2ms/step
Epoch 69/100
6/6 - 0s - loss: 173109.2500 - mean_absolute_error: 306.1772 - val_loss: 173051.7031 - val_mean_absolute_error: 300.9500 - 10ms/epoch - 2ms/step
Epoch 70/100
6/6 - 0s - loss: 168656.6875 - mean_absolute_error: 302.3683 - val_loss: 172337.4688 - val_mean_absolute_error: 300.4461 - 10ms/epoch - 2ms/step
Epoch 71/100
6/6 - 0s - loss: 168241.8906 - mean_absolute_error: 305.4611 - val_loss: 171562.3750 - val_mean_absolute_error: 299.8957 - 10ms/epoch - 2ms/step
Epoch 72/100
6/6 - 0s - loss: 174747.5469 - mean_absolute_error: 305.8458 - val_loss: 170867.6719 - val_mean_absolute_error: 299.4126 - 10ms/epoch - 2ms/step
Epoch 73/100
6/6 - 0s - loss: 167708.0625 - mean_absolute_error: 300.0524 - val_loss: 170178.1250 - val_mean_absolute_error: 298.9043 - 10ms/epoch - 2ms/step
Epoch 74/100
6/6 - 0s - loss: 164724.6406 - mean_absolute_error: 298.4173 - val_loss: 169538.9844 - val_mean_absolute_error: 298.4466 - 10ms/epoch - 2ms/step
Epoch 75/100
6/6 - 0s - loss: 167421.7344 - mean_absolute_error: 301.6310 - val_loss: 168864.8906 - val_mean_absolute_error: 297.9687 - 10ms/epoch - 2ms/step
Epoch 76/100
6/6 - 0s - loss: 156880.8281 - mean_absolute_error: 290.1782 - val_loss: 168046.8281 - val_mean_absolute_error: 297.4010 - 10ms/epoch - 2ms/step
Epoch 77/100
6/6 - 0s - loss: 172090.8438 - mean_absolute_error: 301.5337 - val_loss: 167459.1562 - val_mean_absolute_error: 297.0109 - 10ms/epoch - 2ms/step
Epoch 78/100
6/6 - 0s - loss: 158308.9844 - mean_absolute_error: 288.4727 - val_loss: 166537.6250 - val_mean_absolute_error: 296.4000 - 10ms/epoch - 2ms/step
Epoch 79/100
6/6 - 0s - loss: 165596.5625 - mean_absolute_error: 300.0760 - val_loss: 165985.4219 - val_mean_absolute_error: 296.0335 - 10ms/epoch - 2ms/step
Epoch 80/100
6/6 - 0s - loss: 162148.2344 - mean_absolute_error: 291.6425 - val_loss: 165220.5938 - val_mean_absolute_error: 295.5233 - 10ms/epoch - 2ms/step
Epoch 81/100
6/6 - 0s - loss: 160477.7188 - mean_absolute_error: 289.6206 - val_loss: 164287.2344 - val_mean_absolute_error: 294.8886 - 10ms/epoch - 2ms/step
Epoch 82/100
6/6 - 0s - loss: 160635.3281 - mean_absolute_error: 298.0116 - val_loss: 163803.0156 - val_mean_absolute_error: 294.5776 - 10ms/epoch - 2ms/step
Epoch 83/100
6/6 - 0s - loss: 163757.0156 - mean_absolute_error: 296.9025 - val_loss: 163126.9375 - val_mean_absolute_error: 294.1051 - 10ms/epoch - 2ms/step
Epoch 84/100
6/6 - 0s - loss: 160157.9219 - mean_absolute_error: 294.1176 - val_loss: 162601.8906 - val_mean_absolute_error: 293.7404 - 10ms/epoch - 2ms/step
Epoch 85/100
6/6 - 0s - loss: 163483.1406 - mean_absolute_error: 298.0333 - val_loss: 162099.8906 - val_mean_absolute_error: 293.4064 - 10ms/epoch - 2ms/step
Epoch 86/100
6/6 - 0s - loss: 170440.5938 - mean_absolute_error: 298.7891 - val_loss: 161610.6719 - val_mean_absolute_error: 293.0703 - 10ms/epoch - 2ms/step
Epoch 87/100
6/6 - 0s - loss: 161327.3750 - mean_absolute_error: 287.1638 - val_loss: 161009.3750 - val_mean_absolute_error: 292.6616 - 10ms/epoch - 2ms/step
Epoch 88/100
6/6 - 0s - loss: 165157.0156 - mean_absolute_error: 299.6842 - val_loss: 160366.1094 - val_mean_absolute_error: 292.1998 - 11ms/epoch - 2ms/step
Epoch 89/100
6/6 - 0s - loss: 161044.0000 - mean_absolute_error: 292.1566 - val_loss: 159809.1875 - val_mean_absolute_error: 291.7927 - 11ms/epoch - 2ms/step
Epoch 90/100
6/6 - 0s - loss: 168033.1875 - mean_absolute_error: 296.5432 - val_loss: 159364.3281 - val_mean_absolute_error: 291.4778 - 11ms/epoch - 2ms/step
Epoch 91/100
6/6 - 0s - loss: 161439.8281 - mean_absolute_error: 296.5075 - val_loss: 159055.7031 - val_mean_absolute_error: 291.2720 - 11ms/epoch - 2ms/step
Epoch 92/100
6/6 - 0s - loss: 158791.5938 - mean_absolute_error: 296.7587 - val_loss: 158414.5156 - val_mean_absolute_error: 290.7871 - 11ms/epoch - 2ms/step
Epoch 93/100
6/6 - 0s - loss: 164824.7344 - mean_absolute_error: 297.2034 - val_loss: 157801.2188 - val_mean_absolute_error: 290.3240 - 11ms/epoch - 2ms/step
Epoch 94/100
6/6 - 0s - loss: 158830.5469 - mean_absolute_error: 289.4900 - val_loss: 157343.2031 - val_mean_absolute_error: 289.9822 - 11ms/epoch - 2ms/step
Epoch 95/100
6/6 - 0s - loss: 181642.2344 - mean_absolute_error: 304.7470 - val_loss: 157108.0156 - val_mean_absolute_error: 289.8257 - 11ms/epoch - 2ms/step
Epoch 96/100
6/6 - 0s - loss: 154512.0625 - mean_absolute_error: 286.2135 - val_loss: 156499.1719 - val_mean_absolute_error: 289.3674 - 11ms/epoch - 2ms/step
Epoch 97/100
6/6 - 0s - loss: 155294.1406 - mean_absolute_error: 291.5026 - val_loss: 156100.0938 - val_mean_absolute_error: 289.0668 - 11ms/epoch - 2ms/step
Epoch 98/100
6/6 - 0s - loss: 159279.6250 - mean_absolute_error: 292.7746 - val_loss: 155605.9531 - val_mean_absolute_error: 288.7023 - 11ms/epoch - 2ms/step
Epoch 99/100
6/6 - 0s - loss: 165397.0156 - mean_absolute_error: 295.0135 - val_loss: 155355.3906 - val_mean_absolute_error: 288.5388 - 11ms/epoch - 2ms/step
Epoch 100/100
6/6 - 0s - loss: 161234.8125 - mean_absolute_error: 300.3837 - val_loss: 154693.6719 - val_mean_absolute_error: 288.0476 - 11ms/epoch - 2ms/step</code></pre>
</div>
</div>
<hr>
<p>When training models this way you keep your eyes on the epoch history to study the behavior of the loss function and other metrics on training and test data sets. You have to make a judgement call as to when the optimization has stabilized and further progress is minimal. Alternatively, you can install a function that stops the optimization when certain conditions are met.</p>
<p>This is done in the following code with the <code>callback_early_stopping</code> callback function (not run here). The options of the early stopping function ask it to monitor the loss function on the validation data and stop the optimization when the criterion fails to decrease (<code>mode="min"</code>) over 10 epochs (<code>patience=10</code>). Any change of the monitored metric has to be at least 0.1 in magnitude to qualify as an improvement (<code>min_delta=.1</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>early_stopping <span class="ot">&lt;-</span> <span class="fu">callback_early_stopping</span>(<span class="at">monitor =</span> <span class="st">'val_loss'</span>, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">patience =</span> <span class="dv">10</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">min_delta =</span> .<span class="dv">1</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">mode=</span><span class="st">"min"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>firstANN <span class="sc">%&gt;%</span> </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(x[<span class="sc">-</span>testid, ], </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        y[<span class="sc">-</span>testid], </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">epochs=</span><span class="dv">400</span>, </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">batch_size=</span><span class="dv">32</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">validation_data=</span> <span class="fu">list</span>(x[testid, ], y[testid])</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">callbacks=</span><span class="fu">c</span>(early_stopping)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To see a list of all Keras callback functions type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>?keras<span class="sc">::</span>call</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>at the console prompt.</p>
<hr>
<p>Finally, we predict from the final model, and evaluate its performance on the test data. Due to the use of random elements in the fit (stochastic gradient descent, random dropout, …), the results vary slightly with each fit. Unfortunately the <code>set.seed()</code> function does not ensure identical results (since the fitting is done in <code>python</code>), so your results will differ slightly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>predvals <span class="ot">&lt;-</span> <span class="fu">predict</span>(firstANN, x[testid, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3/3 - 0s - 30ms/epoch - 10ms/step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(y[testid] <span class="sc">-</span> predvals))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 288.0476</code></pre>
</div>
</div>
</section>
<section id="random-numbers" class="level4">
<h4 class="anchored" data-anchor-id="random-numbers">Random numbers</h4>
<p>An aspect of Keras that can be befuddling to <code>R</code> users is lack of control over the random mechanisms during training. Neural networks rely on random numbers for picking starting values, selecting observations into mini batches, selecting neurons in dropout layers, etc.</p>
<p>Since the code executes in Python, the <code>set.seed()</code> operation does not have the intended effect of fixing the sequence of generated random numbers. The underlying Python code relies on the NumPy random number generator. TensorFlow has its own random number generator on top of that. Python code that uses Keras with the TensorFlow backend needs to set the seed for the NumPy and the TensorFlow generator to obtain reproducible results:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>from numpy.random import seed</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>seed(1)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>from tensorflow import set_random_seed</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>set_random_seed(2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>R</code> user is unfortunately out of luck.</p>
<p>If it is any consolation, running Keras in Python might still generate non-reproducible results. You might also need to set the seed in the <code>random</code> Python library. Multi-threading operations on CPUs—and GPUs in particular—can produce a non-deterministic order of operations.</p>
<p>One recommendation to deal with non-deterministic results is training the model several times and averaging the results, essentially ensembling them. When a ingle training run takes several hours, doing it thirty times is not practical.</p>
</section>
</section>
<section id="sec-mnist-analysis-ann" class="level3">
<h3 class="anchored" data-anchor-id="sec-mnist-analysis-ann">MNIST Image Classification</h3>
<p>We now return to the MNIST image classification data introduced in <a href="ann.html#sec-mnist-first-look" class="quarto-xref"><span>Section 31.4</span></a>. Recall that the data comprise 60,000 training images and 10,000 test images of handwritten digits (0–9). Each image has 28 x 28 pixels recording a grayscale value.</p>
<p>The MNIST data is provided by Keras:</p>
<section id="setup-the-data" class="level4">
<h4 class="anchored" data-anchor-id="setup-the-data">Setup the data</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mnist <span class="ot">&lt;-</span> <span class="fu">dataset_mnist</span>()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> mnist<span class="sc">$</span>train<span class="sc">$</span>x</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>g_train <span class="ot">&lt;-</span> mnist<span class="sc">$</span>train<span class="sc">$</span>y</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> mnist<span class="sc">$</span>test<span class="sc">$</span>x</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>g_test <span class="ot">&lt;-</span> mnist<span class="sc">$</span>test<span class="sc">$</span>y</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(x_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60000    28    28</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(x_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10000    28    28</code></pre>
</div>
</div>
<p>The images are stored as a three-dimensional array, and need to be reshaped into a matrix. For classification tasks with <span class="math inline">\(k\)</span> categories, Keras expects as the target values a matrix of <span class="math inline">\(k\)</span> columns. Column <span class="math inline">\(k\)</span> contains ones in the rows for observations where the observed category is <span class="math inline">\(k\)</span>, and zeros otherwise. This is called one-hot encoding of the target variable. Luckily, <code>keras</code> has built-in functions that handle both tasks for us.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> <span class="fu">array_reshape</span>(x_train, <span class="fu">c</span>(<span class="fu">nrow</span>(x_train), <span class="dv">784</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>x_test  <span class="ot">&lt;-</span> <span class="fu">array_reshape</span>(x_test, <span class="fu">c</span>(<span class="fu">nrow</span>(x_test), <span class="dv">784</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> <span class="fu">to_categorical</span>(g_train, <span class="dv">10</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>y_test  <span class="ot">&lt;-</span> <span class="fu">to_categorical</span>(g_test, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at the one-hot encoding of the target data. <code>g_test</code> contains the value of the digit from 0–9. <code>y_test</code> is a matrix with 10 columns, each column corresponds to one digit. If observation <span class="math inline">\(i\)</span> represents digit <span class="math inline">\(j\)</span> then there is a 1 in row <span class="math inline">\(i\)</span>, column <span class="math inline">\(j+1\)</span> of the encoded matrix. For example, for the first twenty images:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>g_test[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>y_test[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    0    0    0    0    0    0    0    1    0     0
 [2,]    0    0    1    0    0    0    0    0    0     0
 [3,]    0    1    0    0    0    0    0    0    0     0
 [4,]    1    0    0    0    0    0    0    0    0     0
 [5,]    0    0    0    0    1    0    0    0    0     0
 [6,]    0    1    0    0    0    0    0    0    0     0
 [7,]    0    0    0    0    1    0    0    0    0     0
 [8,]    0    0    0    0    0    0    0    0    0     1
 [9,]    0    0    0    0    0    1    0    0    0     0
[10,]    0    0    0    0    0    0    0    0    0     1
[11,]    1    0    0    0    0    0    0    0    0     0
[12,]    0    0    0    0    0    0    1    0    0     0
[13,]    0    0    0    0    0    0    0    0    0     1
[14,]    1    0    0    0    0    0    0    0    0     0
[15,]    0    1    0    0    0    0    0    0    0     0
[16,]    0    0    0    0    0    1    0    0    0     0
[17,]    0    0    0    0    0    0    0    0    0     1
[18,]    0    0    0    0    0    0    0    1    0     0
[19,]    0    0    0    1    0    0    0    0    0     0
[20,]    0    0    0    0    1    0    0    0    0     0</code></pre>
</div>
</div>
<p>Let’s look at the matrix of inputs. The next array shows the 28 x 28 - 784 input columns for the third image. The values are grayscale values between 0 and 255.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>x_test[<span class="dv">3</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 [19]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 [37]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 [55]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 [73]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 [91]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[109]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[127]   0   0  38 254 109   0   0   0   0   0   0   0   0   0   0   0   0   0
[145]   0   0   0   0   0   0   0   0   0   0   0   0  87 252  82   0   0   0
[163]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[181]   0   0   0   0 135 241   0   0   0   0   0   0   0   0   0   0   0   0
[199]   0   0   0   0   0   0   0   0   0   0   0   0   0  45 244 150   0   0
[217]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[235]   0   0   0   0   0  84 254  63   0   0   0   0   0   0   0   0   0   0
[253]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 202 223  11
[271]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[289]   0   0   0   0   0   0  32 254 216   0   0   0   0   0   0   0   0   0
[307]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  95 254
[325] 195   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[343]   0   0   0   0   0   0   0   0 140 254  77   0   0   0   0   0   0   0
[361]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  57
[379] 237 205   8   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[397]   0   0   0   0   0   0   0   0   0 124 255 165   0   0   0   0   0   0
[415]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[433]   0 171 254  81   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[451]   0   0   0   0   0   0   0   0   0   0  24 232 215   0   0   0   0   0
[469]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[487]   0   0 120 254 159   0   0   0   0   0   0   0   0   0   0   0   0   0
[505]   0   0   0   0   0   0   0   0   0   0   0   0 151 254 142   0   0   0
[523]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[541]   0   0   0   0 228 254  66   0   0   0   0   0   0   0   0   0   0   0
[559]   0   0   0   0   0   0   0   0   0   0   0   0   0  61 251 254  66   0
[577]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[595]   0   0   0   0   0 141 254 205   3   0   0   0   0   0   0   0   0   0
[613]   0   0   0   0   0   0   0   0   0   0   0   0   0   0  10 215 254 121
[631]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[649]   0   0   0   0   0   0   5 198 176  10   0   0   0   0   0   0   0   0
[667]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[685]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[703]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[721]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[739]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[757]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[775]   0   0   0   0   0   0   0   0   0   0</code></pre>
</div>
</div>
<p>Finally, prior to training the network, we scale the input values to lie between 0–1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> x_train <span class="sc">/</span> <span class="dv">255</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>x_test  <span class="ot">&lt;-</span> x_test <span class="sc">/</span> <span class="dv">255</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The target variable does not need to be scaled, the one-hot encoding together with the use of a softmax output function ensures that the output for each category is a value between 0 and 1, and that they sum to 1 across the 10 categories. We will interpret them as predicted probabilities that an observed image is assigned to a particular digit.</p>
<p>To classify the MNIST images we consider two types of neural networks in the remainder of this chapter: a multi layer ANN and a network without a hidden layer. The latter is a multi category perceptron and very similar to a multinomial logistic regression model.</p>
</section>
<section id="multi-layer-neural-network" class="level4">
<h4 class="anchored" data-anchor-id="multi-layer-neural-network">Multi layer neural network</h4>
<p>We now train the network shown in <a href="ann.html#fig-mnist-2-layer" class="quarto-xref">Figure&nbsp;<span>31.14</span></a>, an ANN with two hidden layers. We also add dropout regularization layers after each fully connected hidden layer. The first layer specifies the input shape of 28 x 28 = 784. It has 128 neurons and ReLU activation. Why? Because.</p>
<p>This is followed by a first dropout layer with rate <span class="math inline">\(\phi_1 = 0.3\)</span>, another fully connected hidden layer with 64 nodes and hyperbolic tangent activation function, a second dropout layer with rate <span class="math inline">\(\phi_2 = 0.2\)</span>, and a final softmax output layer. Why? Because.</p>
<section id="setup-the-network" class="level5">
<h5 class="anchored" data-anchor-id="setup-the-network">Setup the network</h5>
<p>The following statements set up the network in <code>keras</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>modelnn <span class="ot">&lt;-</span> <span class="fu">keras_model_sequential</span>() <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">128</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">activation=</span><span class="st">"relu"</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">input_shape=</span><span class="dv">784</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">name=</span><span class="st">"FirstHidden"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dropout</span>(<span class="at">rate=</span><span class="fl">0.3</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">name=</span><span class="st">"FirstDropOut"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">64</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">activation=</span><span class="st">"tanh"</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">name=</span><span class="st">"SecondHidden"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dropout</span>(<span class="at">rate=</span><span class="fl">0.2</span>,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">name=</span><span class="st">"SecondDropOut"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">10</span>, </span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">activation=</span><span class="st">"softmax"</span>,</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">name=</span><span class="st">"Output"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>summary()</code> function let’s us inspect whether we got it all right.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelnn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model: "sequential_1"
________________________________________________________________________________
 Layer (type)                       Output Shape                    Param #     
================================================================================
 FirstHidden (Dense)                (None, 128)                     100480      
 FirstDropOut (Dropout)             (None, 128)                     0           
 SecondHidden (Dense)               (None, 64)                      8256        
 SecondDropOut (Dropout)            (None, 64)                      0           
 Output (Dense)                     (None, 10)                      650         
================================================================================
Total params: 109386 (427.29 KB)
Trainable params: 109386 (427.29 KB)
Non-trainable params: 0 (0.00 Byte)
________________________________________________________________________________</code></pre>
</div>
</div>
<p>The total number of parameters in this network is 109,386, a sizeable network but not a huge network.</p>
</section>
<section id="set-up-the-optimization" class="level5">
<h5 class="anchored" data-anchor-id="set-up-the-optimization">Set up the optimization</h5>
<p>Next, we add details to the model to specify the fitting algorithm. We fit the model by minimizing the categorical cross-entropy function and monitor the classification accuracy during the iterations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>modelnn <span class="sc">%&gt;%</span> <span class="fu">compile</span>(<span class="at">loss=</span><span class="st">"categorical_crossentropy"</span>,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">optimizer=</span><span class="fu">optimizer_rmsprop</span>(), </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">metrics=</span><span class="fu">c</span>(<span class="st">"accuracy"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fit-the-model" class="level5">
<h5 class="anchored" data-anchor-id="fit-the-model">Fit the model</h5>
<p>We are ready to go. The final step is to supply training data, and fit the model. With a batch size of 128 observations, each epoch corresponds to 60,000 / 128 = 469 gradient evaluations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>history <span class="ot">&lt;-</span> modelnn <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">fit</span>(x_train, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>          y_train, </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">epochs=</span><span class="dv">20</span>, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">batch_size=</span><span class="dv">128</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">validation_data=</span> <span class="fu">list</span>(x_test, y_test),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>          )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/20
469/469 - 1s - loss: 0.3945 - accuracy: 0.8857 - val_loss: 0.1667 - val_accuracy: 0.9476 - 838ms/epoch - 2ms/step
Epoch 2/20
469/469 - 1s - loss: 0.1885 - accuracy: 0.9439 - val_loss: 0.1197 - val_accuracy: 0.9636 - 548ms/epoch - 1ms/step
Epoch 3/20
469/469 - 1s - loss: 0.1496 - accuracy: 0.9547 - val_loss: 0.0992 - val_accuracy: 0.9701 - 541ms/epoch - 1ms/step
Epoch 4/20
469/469 - 1s - loss: 0.1240 - accuracy: 0.9622 - val_loss: 0.0906 - val_accuracy: 0.9730 - 555ms/epoch - 1ms/step
Epoch 5/20
469/469 - 1s - loss: 0.1115 - accuracy: 0.9661 - val_loss: 0.0853 - val_accuracy: 0.9744 - 554ms/epoch - 1ms/step
Epoch 6/20
469/469 - 1s - loss: 0.1004 - accuracy: 0.9688 - val_loss: 0.0763 - val_accuracy: 0.9776 - 551ms/epoch - 1ms/step
Epoch 7/20
469/469 - 1s - loss: 0.0965 - accuracy: 0.9708 - val_loss: 0.0742 - val_accuracy: 0.9783 - 581ms/epoch - 1ms/step
Epoch 8/20
469/469 - 1s - loss: 0.0877 - accuracy: 0.9734 - val_loss: 0.0748 - val_accuracy: 0.9767 - 559ms/epoch - 1ms/step
Epoch 9/20
469/469 - 1s - loss: 0.0837 - accuracy: 0.9741 - val_loss: 0.0731 - val_accuracy: 0.9781 - 562ms/epoch - 1ms/step
Epoch 10/20
469/469 - 1s - loss: 0.0794 - accuracy: 0.9750 - val_loss: 0.0751 - val_accuracy: 0.9773 - 558ms/epoch - 1ms/step
Epoch 11/20
469/469 - 1s - loss: 0.0750 - accuracy: 0.9765 - val_loss: 0.0686 - val_accuracy: 0.9803 - 555ms/epoch - 1ms/step
Epoch 12/20
469/469 - 1s - loss: 0.0703 - accuracy: 0.9773 - val_loss: 0.0696 - val_accuracy: 0.9805 - 544ms/epoch - 1ms/step
Epoch 13/20
469/469 - 1s - loss: 0.0688 - accuracy: 0.9786 - val_loss: 0.0724 - val_accuracy: 0.9787 - 550ms/epoch - 1ms/step
Epoch 14/20
469/469 - 1s - loss: 0.0645 - accuracy: 0.9796 - val_loss: 0.0709 - val_accuracy: 0.9795 - 544ms/epoch - 1ms/step
Epoch 15/20
469/469 - 1s - loss: 0.0637 - accuracy: 0.9808 - val_loss: 0.0731 - val_accuracy: 0.9786 - 547ms/epoch - 1ms/step
Epoch 16/20
469/469 - 1s - loss: 0.0616 - accuracy: 0.9804 - val_loss: 0.0718 - val_accuracy: 0.9784 - 552ms/epoch - 1ms/step
Epoch 17/20
469/469 - 1s - loss: 0.0604 - accuracy: 0.9808 - val_loss: 0.0665 - val_accuracy: 0.9802 - 559ms/epoch - 1ms/step
Epoch 18/20
469/469 - 1s - loss: 0.0573 - accuracy: 0.9819 - val_loss: 0.0666 - val_accuracy: 0.9800 - 558ms/epoch - 1ms/step
Epoch 19/20
469/469 - 1s - loss: 0.0565 - accuracy: 0.9823 - val_loss: 0.0729 - val_accuracy: 0.9785 - 536ms/epoch - 1ms/step
Epoch 20/20
469/469 - 1s - loss: 0.0550 - accuracy: 0.9824 - val_loss: 0.0719 - val_accuracy: 0.9789 - 617ms/epoch - 1ms/step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(history, <span class="at">smooth =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="ann_R_files/figure-html/mnist_data_fit-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="ann_R_files/figure-html/mnist_data_fit-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>After about 10 epochs the training and validation accuracy are stabilizing although the loss continues to decrease. Interestingly, the accuracy and loss in the 10,000 image validation set is better than in the 60,000 image training data set. Considering that the grayscale values are entered into this neural network as 784 numeric input variables without taking into account any spatial arrangement of the pixels on the image, a classification accuracy of 96% on unseen images is quite good. Whether that is sufficient depends on the application.</p>
<p>As we will see in <a href="deeplearning.html" class="quarto-xref"><span>Chapter 34</span></a>, neural networks that specialize in the processing of grid-like data such as images easily improve on this performance.</p>
</section>
<section id="calculate-predicted-categories" class="level5">
<h5 class="anchored" data-anchor-id="calculate-predicted-categories">Calculate predicted categories</h5>
<p>To calculate the predicted categories for the images in the test data set, we use the <code>predict</code> function. The result of that operation is a vector of 10 predicted <em>probabilities</em> for each observation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>predvals <span class="ot">&lt;-</span> modelnn <span class="sc">%&gt;%</span> <span class="fu">predict</span>(x_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>313/313 - 0s - 106ms/epoch - 338us/step</code></pre>
</div>
</div>
<p>For the first image, the probabilities that its digit belongs to any of the 10 classes is given by this vector</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(predvals[<span class="dv">1</span>,],<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0 0 0 0 0 0 0 1 0 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(predvals[<span class="dv">1</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>The maximum probability is 1 in position 8. The image is classified as a “7” (the digits are 0-based).</p>
<p><code>keras</code> provides the convenience function <code>k_argmax()</code> to perform this operation; it returns the index of the maximum value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>predcl <span class="ot">&lt;-</span> modelnn <span class="sc">%&gt;%</span> <span class="fu">predict</span>(x_test) <span class="sc">%&gt;%</span> <span class="fu">k_argmax</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>313/313 - 0s - 98ms/epoch - 313us/step</code></pre>
</div>
</div>
<p>Which of the first 500 observations were misclassified?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>miscl <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">as.numeric</span>(predcl[<span class="dv">1</span><span class="sc">:</span><span class="dv">500</span>]) <span class="sc">!=</span> g_test[<span class="dv">1</span><span class="sc">:</span><span class="dv">500</span>])</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>miscl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   9 248 260 322 341 360 382 446</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Observed value for obs # "</span>, miscl[<span class="dv">1</span>], <span class="st">":"</span>, g_test[miscl[<span class="dv">1</span>]],<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observed value for obs #  9 : 5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicted valie for obs #"</span>, miscl[<span class="dv">1</span>], <span class="st">":"</span>, <span class="fu">as.numeric</span>(predcl[miscl[<span class="dv">1</span>]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted valie for obs # 9 : 6</code></pre>
</div>
</div>
<p>The first misclassified observation is #9. The observed digit value is 5, the predicted value is 6. The softmax probabilities for this observation show why it predicted category 6:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(predvals[miscl[<span class="dv">1</span>],],<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.0000 0.0000 0.0000 0.0000 0.0001 0.3026 0.6967 0.0000 0.0001 0.0005</code></pre>
</div>
</div>
<p>We can visualize the data with the <code>image</code> function. The next code segment does this for the first observation in the data set and for the first two mis-classified observations:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize the digits</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>plotIt <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">id=</span><span class="dv">1</span>) {</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    im <span class="ot">&lt;-</span> mnist<span class="sc">$</span>test<span class="sc">$</span>x[id,,]</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    im <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">apply</span>(im, <span class="dv">2</span>, rev)) </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">image</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">28</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">28</span>, </span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>          im, </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">col=</span><span class="fu">gray</span>((<span class="dv">0</span><span class="sc">:</span><span class="dv">255</span>)<span class="sc">/</span><span class="dv">255</span>), </span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">xaxt=</span><span class="st">'n'</span>, </span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">main=</span><span class="fu">paste</span>(<span class="st">"Observation #"</span>,id,<span class="st">"--"</span>,</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Image label: "</span>,g_test[id], </span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>                     <span class="st">" Predicted: "</span>, <span class="fu">as.numeric</span>(predcl[id])))</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plotIt</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ann_R_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotIt</span>(miscl[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ann_R_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotIt</span>(miscl[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ann_R_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-ann-multinomial" class="level4">
<h4 class="anchored" data-anchor-id="sec-ann-multinomial">Multinomial logistic regression</h4>
<p>A 96% accuracy is impressive, but maybe it is not good enough. In applications where the consequences of errors are high, this accuracy might be insufficient. Suppose we are using the trained network to recognize written digits on personal checks. Getting 400 out of 10,000 digits wrong would be unacceptable. Banks would deposit incorrect amounts all the time.</p>
<p>If that is the application for the trained algorithm, we should consider other models for these data. This raises an interesting question: how much did we gain by adding the layers of the network? If this is an effective strategy to increase accuracy then we could consider adding more layers. If not, then maybe we need to research an entirely different network architecture.</p>
<p>Before trying deeper alternatives we can establish one performance benchmark by removing the hidden layers and training what essentially is a single layer <strong>perceptron</strong> (<a href="ann.html#sec-ann-intro" class="quarto-xref"><span>Section 31.1</span></a>). This model has an input layer and an output layer. In terms of the <code>keras</code> syntax it is specified with a single layer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>modellr <span class="ot">&lt;-</span> <span class="fu">keras_model_sequential</span>() <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">layer_dense</span>(<span class="at">input_shape=</span><span class="dv">784</span>, </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">units=</span><span class="dv">10</span>,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">activation=</span><span class="st">"softmax"</span>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modellr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model: "sequential_2"
________________________________________________________________________________
 Layer (type)                       Output Shape                    Param #     
================================================================================
 dense_1 (Dense)                    (None, 10)                      7850        
================================================================================
Total params: 7850 (30.66 KB)
Trainable params: 7850 (30.66 KB)
Non-trainable params: 0 (0.00 Byte)
________________________________________________________________________________</code></pre>
</div>
</div>
<p>This is essentially a multinomial logistic regression model with a 10-category target variable and 784 input variables. The model is much smaller than the previous network (it has <em>only</em> 7,850 parameters) but is huge if we think of it as a multinomial logistic regression model. Many software packages for multinomial regression would struggle to fit a model of this size. When articulated as a neural network, training such a model is actually a breeze.</p>
<p>We proceed just as before.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>modellr <span class="sc">%&gt;%</span> <span class="fu">compile</span>(<span class="at">loss =</span> <span class="st">"categorical_crossentropy"</span>,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">optimizer =</span> <span class="fu">optimizer_rmsprop</span>(), </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">"accuracy"</span>))</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>history <span class="ot">&lt;-</span> modellr <span class="sc">%&gt;%</span> <span class="fu">fit</span>(x_train, </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>                y_train, </span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">epochs=</span><span class="dv">20</span>,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">batch_size=</span><span class="dv">128</span>,</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">validation_data=</span><span class="fu">list</span>(x_test, y_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/20
469/469 - 0s - loss: 0.5891 - accuracy: 0.8555 - val_loss: 0.3443 - val_accuracy: 0.9076 - 421ms/epoch - 897us/step
Epoch 2/20
469/469 - 0s - loss: 0.3326 - accuracy: 0.9073 - val_loss: 0.3031 - val_accuracy: 0.9161 - 240ms/epoch - 511us/step
Epoch 3/20
469/469 - 0s - loss: 0.3046 - accuracy: 0.9155 - val_loss: 0.2871 - val_accuracy: 0.9194 - 236ms/epoch - 503us/step
Epoch 4/20
469/469 - 0s - loss: 0.2910 - accuracy: 0.9187 - val_loss: 0.2791 - val_accuracy: 0.9231 - 226ms/epoch - 481us/step
Epoch 5/20
469/469 - 0s - loss: 0.2831 - accuracy: 0.9212 - val_loss: 0.2761 - val_accuracy: 0.9235 - 225ms/epoch - 480us/step
Epoch 6/20
469/469 - 0s - loss: 0.2774 - accuracy: 0.9226 - val_loss: 0.2734 - val_accuracy: 0.9250 - 224ms/epoch - 479us/step
Epoch 7/20
469/469 - 0s - loss: 0.2733 - accuracy: 0.9238 - val_loss: 0.2710 - val_accuracy: 0.9261 - 225ms/epoch - 479us/step
Epoch 8/20
469/469 - 0s - loss: 0.2700 - accuracy: 0.9249 - val_loss: 0.2726 - val_accuracy: 0.9240 - 225ms/epoch - 479us/step
Epoch 9/20
469/469 - 0s - loss: 0.2671 - accuracy: 0.9263 - val_loss: 0.2669 - val_accuracy: 0.9255 - 229ms/epoch - 488us/step
Epoch 10/20
469/469 - 0s - loss: 0.2650 - accuracy: 0.9270 - val_loss: 0.2653 - val_accuracy: 0.9257 - 225ms/epoch - 479us/step
Epoch 11/20
469/469 - 0s - loss: 0.2629 - accuracy: 0.9276 - val_loss: 0.2668 - val_accuracy: 0.9263 - 226ms/epoch - 482us/step
Epoch 12/20
469/469 - 0s - loss: 0.2613 - accuracy: 0.9279 - val_loss: 0.2668 - val_accuracy: 0.9266 - 224ms/epoch - 478us/step
Epoch 13/20
469/469 - 0s - loss: 0.2599 - accuracy: 0.9290 - val_loss: 0.2667 - val_accuracy: 0.9261 - 223ms/epoch - 475us/step
Epoch 14/20
469/469 - 0s - loss: 0.2586 - accuracy: 0.9293 - val_loss: 0.2652 - val_accuracy: 0.9270 - 227ms/epoch - 485us/step
Epoch 15/20
469/469 - 0s - loss: 0.2574 - accuracy: 0.9296 - val_loss: 0.2660 - val_accuracy: 0.9262 - 224ms/epoch - 478us/step
Epoch 16/20
469/469 - 0s - loss: 0.2563 - accuracy: 0.9306 - val_loss: 0.2638 - val_accuracy: 0.9279 - 230ms/epoch - 490us/step
Epoch 17/20
469/469 - 0s - loss: 0.2553 - accuracy: 0.9307 - val_loss: 0.2639 - val_accuracy: 0.9276 - 227ms/epoch - 483us/step
Epoch 18/20
469/469 - 0s - loss: 0.2540 - accuracy: 0.9309 - val_loss: 0.2650 - val_accuracy: 0.9282 - 229ms/epoch - 488us/step
Epoch 19/20
469/469 - 0s - loss: 0.2533 - accuracy: 0.9316 - val_loss: 0.2635 - val_accuracy: 0.9278 - 226ms/epoch - 481us/step
Epoch 20/20
469/469 - 0s - loss: 0.2526 - accuracy: 0.9312 - val_loss: 0.2650 - val_accuracy: 0.9274 - 227ms/epoch - 483us/step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(history, <span class="at">smooth =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="ann_R_files/figure-html/mnist_percep_fit-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="ann_R_files/figure-html/mnist_percep_fit-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Even with just a single layer, the model performs quite well, its accuracy is around 92%. Adding the additional layer in the previous ANN did improve the accuracy. On the other hand, it took more than 100,000 extra parameters to move from 92% to 96% accuracy.</p>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;33.1: Epoch history for the first 200 epochs.</span>
</div>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./training_ann.html" class="pagination-link" aria-label="Training Neural Networks">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Training Neural Networks</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./deeplearning.html" class="pagination-link" aria-label="Deep Learning">
        <span class="nav-page-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Deep Learning</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Statistical Learning by Oliver Schabenberger</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"openEffect":"zoom","loop":false,"selector":".lightbox","closeEffect":"zoom","descPosition":"bottom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>