<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Learning - 12&nbsp; Local Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./class_reg.html" rel="next">
<link href="./regdiscrete.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./regintro.html">Supervised Learning I: Regression</a></li><li class="breadcrumb-item"><a href="./reglocal.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Local Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Learning</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Foundation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statmodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./biasvariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bias Variance Tradeoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linalg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Algebra Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Parameter Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./learningtypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Types of Statistical Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Supervised Learning I: Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regintro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regglobal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The Classical Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regfeature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Feature Selection and Regularization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regnlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Nonlinear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regdiscrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Discrete Target Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reglocal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Local Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Supervised Learning II: Classification</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./class_reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regression Approach to Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discriminant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Discriminant Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./naivebayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Naive Bayes Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./supportvectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Support Vectors</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Decision Trees</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Ensemble Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ensemble_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Introduction to Ensemble Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bagging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Bagging</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./boosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Boosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bayesian Model Averaging</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Unsupervised Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unsuper_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Introduction to Unsupervised Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Principal Component Analysis (PCA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Cluster Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mbc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Model-based Clustering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Association Rules</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Supervised Learning III: Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Generalized Additive Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./corrdata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Correlated Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mixed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Mixed Models for Longitudinal Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">Neural Networks and Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Artificial Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./training_ann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Training Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ann_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Neural Networks in <code>R</code> (with Keras)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./deeplearning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Deep Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">Explainability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explainability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Interpretability and Explainability</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#kernel-regression" id="toc-kernel-regression" class="nav-link active" data-scroll-target="#kernel-regression"><span class="header-section-number">12.1</span> Kernel Regression</a>
  <ul>
  <li><a href="#nadaraya-watson-estimator" id="toc-nadaraya-watson-estimator" class="nav-link" data-scroll-target="#nadaraya-watson-estimator">Nadaraya-Watson Estimator</a></li>
  <li><a href="#cross-validation-for-lambda" id="toc-cross-validation-for-lambda" class="nav-link" data-scroll-target="#cross-validation-for-lambda">Cross-validation for <span class="math inline">\(\lambda\)</span></a></li>
  </ul></li>
  <li><a href="#local-regression" id="toc-local-regression" class="nav-link" data-scroll-target="#local-regression"><span class="header-section-number">12.2</span> Local Regression</a>
  <ul>
  <li><a href="#choosing-the-degree" id="toc-choosing-the-degree" class="nav-link" data-scroll-target="#choosing-the-degree">Choosing the Degree</a></li>
  <li><a href="#loess-regression" id="toc-loess-regression" class="nav-link" data-scroll-target="#loess-regression">Loess Regression</a></li>
  </ul></li>
  <li><a href="#sec-basis-functions" id="toc-sec-basis-functions" class="nav-link" data-scroll-target="#sec-basis-functions"><span class="header-section-number">12.3</span> Basis Functions</a>
  <ul>
  <li><a href="#segments-knots-and-constraints" id="toc-segments-knots-and-constraints" class="nav-link" data-scroll-target="#segments-knots-and-constraints">Segments, Knots, and Constraints</a></li>
  <li><a href="#basis-function-representation" id="toc-basis-function-representation" class="nav-link" data-scroll-target="#basis-function-representation">Basis Function Representation</a></li>
  <li><a href="#regression-splines" id="toc-regression-splines" class="nav-link" data-scroll-target="#regression-splines">Regression Splines</a></li>
  <li><a href="#sec-smoothing-splines" id="toc-sec-smoothing-splines" class="nav-link" data-scroll-target="#sec-smoothing-splines">Smoothing Splines</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./regintro.html">Supervised Learning I: Regression</a></li><li class="breadcrumb-item"><a href="./reglocal.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Local Models</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-local-models" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Local Models</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In <a href="regintro.html" class="quarto-xref"><span>Chapter 7</span></a> we introduced different approaches to structure the problem of finding <span class="math display">\[
\text{E}[Y_i | \textbf{x}_i] = f^*(\textbf{x}_i)
\]</span> by constraining the model family or the approach to estimation. <a href="regintro.html#sec-local-global-models" class="quarto-xref"><span>Section 7.2</span></a> then introduced the concept of <strong>global</strong> and <strong>local</strong> models.</p>
<p>The methods discussed in this part of the book so far are <strong>global models</strong> in the sense that they depend on parameters <span class="math inline">\(\boldsymbol{\beta}\)</span> that apply regardless of the position <span class="math inline">\(\textbf{x}_0\)</span> in the regression hull. Global models do not have a different set of parameters at <span class="math inline">\(\textbf{x}_i\)</span> and <span class="math inline">\(\textbf{x}_j\)</span>.</p>
<p>In this chapter we discuss in greater detail models that capture local variations of the mean function. The two major approaches to give models greater flexibility is through the introduction of weight functions or through basis expansions. Kernel regression and local polynomials are examples of the weighting approach. Regressions and smoothing splines are examples of the basis expansion approach.</p>
<p>Because these methods suffer from the curse of dimensionality (<a href="regintro.html#sec-curse-dimensionality" class="quarto-xref"><span>Section 7.4.1</span></a>), they are not applied in higher dimensions. For the remainder of this chapter we assume a single input variable, <span class="math inline">\(\textbf{x}= x\)</span>.</p>
<section id="kernel-regression" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="kernel-regression"><span class="header-section-number">12.1</span> Kernel Regression</h2>
<p>A special case of a kernel regression estimator was introduced in <a href="regintro.html#sec-knn-regression" class="quarto-xref"><span>Section 7.4</span></a>, the <span class="math inline">\(k\)</span>-nearest neighbor regression estimator. The idea is simple: to predict the mean of <span class="math inline">\(Y\)</span> at <span class="math inline">\(x_0\)</span>, find the <span class="math inline">\(k\)</span> observations closest to <span class="math inline">\(x_0\)</span> and take their average. The procedure can be formalized as follows:</p>
<ol type="1">
<li><p>The general model is <span class="math inline">\(Y(x) = f(x) + \epsilon\)</span> with <span class="math inline">\(\text{E}[\epsilon] = 0\)</span></p></li>
<li><p>To predict <span class="math inline">\(f(x_0)\)</span> use the local estimator <span class="math inline">\(\widehat{f}(x_0) = \frac{1}{k}\sum_{i=1}^k y(x_{(i)})\)</span> where <span class="math inline">\(x_{(i)}\)</span> is the <span class="math inline">\(i\)</span><sup>th</sup> closest observation to <span class="math inline">\(x_0\)</span> and <span class="math inline">\(y(x_{(i)})\)</span> is the observed value of the target variable at <span class="math inline">\(x_{(i)}\)</span>.</p></li>
<li><p>This is equivalent to considering at <span class="math inline">\(x_0\)</span> the regression model <span class="math display">\[
Y(x_0) = \beta + \epsilon^*
\]</span> in just a neighborhood of <span class="math inline">\(x_0\)</span>. This is an intercept-only model and the OLS estimator is <span class="math inline">\(\widehat{\beta} = \overline{y}\)</span>. To make it so the model uses only the <span class="math inline">\(k\)</span> observations closest to <span class="math inline">\(x_0\)</span> we fit it as a <strong>weighted</strong> regression. The weight of an observation is 1 if it is within the <span class="math inline">\(k\)</span>-neighborhood and 0 if it is outside. Formally, the weight function at <span class="math inline">\(x_0\)</span> is</p></li>
</ol>
<p><span class="math display">\[
K(x_0,x_i) = I(||x_i-x_0|| \le ||x_{(k)} - x_0 ||)
\]</span> where <span class="math inline">\(x_{(k)}\)</span> denotes the observation ranked <span class="math inline">\(k\)</span><sup>th</sup> in distance from <span class="math inline">\(x_0\)</span>, <span class="math inline">\(||x_i-x_0||\)</span> denotes the distance of <span class="math inline">\(x_i\)</span> from the prediction location <span class="math inline">\(x_0\)</span>, and <span class="math inline">\(I()\)</span> is the indicator function (<span class="math inline">\(I(a)\)</span> is 1 if <span class="math inline">\(a\)</span> is true).</p>
<ol start="4" type="1">
<li>When the weight function is applied, the estimator of <span class="math inline">\(\beta\)</span> becomes <span class="math display">\[
\widehat{\beta}(x_0) = \frac{\sum_{i=1}^n K(x_0,x_i) \, y(x_i)}{\sum_{i=1}^n K(x_0,x_i)} = \frac{1}{k}\sum_{i=1}^k y(x_{(i)})
\]</span></li>
</ol>
<p>What have we accomplished with this setup? A global model, <span class="math inline">\(Y(x) = \beta + \epsilon^*\)</span>, which is probably not correct over the range of <span class="math inline">\(X\)</span> has turned into a local model for <span class="math inline">\(Y(x_0)\)</span> by introducing a weight function that gives more weight to observations close to <span class="math inline">\(x_0\)</span> than to observations far away. It is much more reasonable to assume an intercept-only model holds at <span class="math inline">\(x_0\)</span> than across the entire range of <span class="math inline">\(X\)</span>. As the prediction problem moves to another location, say <span class="math inline">\(x^*_0\)</span>, the weighted regression problem is solved again, this time based on the weight function <span class="math display">\[
K(x^*_0,x_i) = I(||x_i-x^*_0|| \le ||x_{(k)} - x^*_0 ||)
\]</span></p>
<p>Rather than one global estimate <span class="math inline">\(\widehat{\boldsymbol{\beta}}\)</span> we get as many estimates as there are points we wish to predict at: <span class="math inline">\(\widehat{\beta}(x_0), \widehat{\beta}(x^*_0), \widehat{\beta}(x^{**}_0), \cdots\)</span>.</p>
<p>The following simulated data is taken from the course on Predictive Modeling by <span class="citation" data-cites="Garcia-Portugues2024">García-Portugués (<a href="references.html#ref-Garcia-Portugues2024" role="doc-biblioref">2024</a>)</span>. The true mean function is <span class="math display">\[
f(x) = x^2 \, \cos(x)
\]</span> and the observed data (<a href="#fig-sim-data-garcia" class="quarto-xref">Figure&nbsp;<span>12.1</span></a>) follow the model <span class="math display">\[
Y(x) = f(x) + \epsilon\quad \epsilon \sim \textit{iid } G(0,4)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>eps <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="cf">function</span>(x) x<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">cos</span>(x)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">m</span>(X) <span class="sc">+</span> eps</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sim-data-garcia" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sim-data-garcia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="reglocal_files/figure-html/fig-sim-data-garcia-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="quarto-lightbox-gallery-1"><img src="reglocal_files/figure-html/fig-sim-data-garcia-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sim-data-garcia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Simulated data according to <span class="citation" data-cites="Garcia-Portugues2024">García-Portugués (<a href="references.html#ref-Garcia-Portugues2024" role="doc-biblioref">2024</a>)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="example">
<div class="example-header">
<p>Example: 3-nearest Neighbor Estimation</p>
</div>
<div class="example-container">
<p>The following code computes the 3-NN regression estimator at a grid of <span class="math inline">\(x_0\)</span> values, ranging from -4 to 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>x_0 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>k3_reg <span class="ot">&lt;-</span> Rfast<span class="sc">::</span><span class="fu">knn</span>(<span class="fu">as.matrix</span>(x_0),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">as.matrix</span>(Y),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">as.matrix</span>(X),<span class="at">k=</span><span class="dv">3</span>,<span class="at">type=</span><span class="st">"R"</span>) </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(x_0,k3_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      x_0           
 [1,]  -4  -9.681715
 [2,]  -3 -10.319916
 [3,]  -2  -2.134633
 [4,]  -1   1.066642
 [5,]   0  -0.755860
 [6,]   1   3.510851
 [7,]   2   1.982169
 [8,]   3  -9.101672
 [9,]   4  -8.201705</code></pre>
</div>
</div>
<p>The same results can be obtained using an intercept-only model with weights calculated according to <span class="math inline">\(K(x_0,x_i)\)</span>. The <code>proxy::dist()</code> function computes the distance between the <span class="math inline">\(x_0\)</span> locations and the <span class="math inline">\(x\)</span> values. The loop constructs the weight vector for each prediction point, assigning 1 to the points within the 3-neighbor distance and 0 to the points outside. The only change in the call to <code>lm()</code> from one prediction point to the next is the vector of weights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> proxy<span class="sc">::</span><span class="fu">dist</span>(x_0,X,<span class="at">method=</span><span class="st">"euclidean"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(x_0)) {</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    d_lim <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">sort</span>(d[i,]),<span class="dv">3</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    w <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">length</span>(X))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    w[<span class="fu">which</span>((d[i,] <span class="sc">&gt;=</span> d_lim[<span class="dv">1</span>] <span class="sc">&amp;</span> (d[i,] <span class="sc">&lt;=</span> d_lim[<span class="dv">3</span>])))] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"x_0: "</span>, x_0[i], <span class="st">"beta_hat: "</span>,<span class="fu">lm</span>(Y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">weights=</span>w)<span class="sc">$</span>coefficients,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x_0:  -4 beta_hat:  -9.681715 
x_0:  -3 beta_hat:  -10.31992 
x_0:  -2 beta_hat:  -2.134633 
x_0:  -1 beta_hat:  1.066642 
x_0:  0 beta_hat:  -0.75586 
x_0:  1 beta_hat:  3.510851 
x_0:  2 beta_hat:  1.982169 
x_0:  3 beta_hat:  -9.101672 
x_0:  4 beta_hat:  -8.201705 </code></pre>
</div>
</div>
</div>
</div>
<section id="nadaraya-watson-estimator" class="level3">
<h3 class="anchored" data-anchor-id="nadaraya-watson-estimator">Nadaraya-Watson Estimator</h3>
<p>The previous estimator is a special case of the Nadaraya-Watson kernel estimator of <span class="math inline">\(f(x_0)\)</span>, <span class="math display">\[
\widehat{f}(x_0) = \frac{\sum_{i=1}^n K_\lambda(x_0,x_i)\,y_i}{\sum_{i=1}^nK_\lambda(x_0,x_i)}=\sum_{i=1}^n w_i(x_0)\,y_i
\]</span></p>
<p>The expression on the right shows that this is a weighted estimator where the weights are given by <span class="math display">\[
w_i(x_0) = \frac{K_\lambda(x_0,x_i)}{\sum_{i=1}^n K_\lambda(x_0,x_i)}
\]</span> The <strong>kernel function</strong> <span class="math inline">\(K_\lambda(x_0,x_i)\)</span> depends on the prediction location <span class="math inline">\(x_0\)</span>, the distance <span class="math inline">\(|x_i-x_0|\)</span> between <span class="math inline">\(x_i\)</span> and <span class="math inline">\(x_0\)</span>, and a parameter <span class="math inline">\(\lambda\)</span> that controls the shape of the kernel. <span class="math inline">\(\lambda\)</span> is called the <strong>bandwidth</strong> of the kernel because it controls how quickly the kernel weights drop with increasing distance from <span class="math inline">\(x_0\)</span>; or in other words, how wide the kernel function is.</p>
<p>Popular kernel functions are</p>
<ol type="1">
<li><p><strong>Epanechnikov</strong> kernel <span class="math display">\[
K_\lambda(x_0,x) = \left \{ \begin{array}{ll} \frac{3}{4}\left(1-t^2\right) &amp; \text{if } |t| \le 1 \\
0 &amp; \text{otherwise} \end{array}\right .
\]</span></p></li>
<li><p><strong>Tricube</strong> kernel <span class="math display">\[
K_\lambda(x_0,x) = \left \{ \begin{array}{ll} \frac{3}{4}\left(1-|t|^3\right)^3 &amp; \text{if } |t| \le 1 \\
0 &amp; \text{otherwise} \end{array}\right .
\]</span></p></li>
<li><p><strong>Gaussian</strong> kernel <span class="math display">\[
K_\lambda(x_0,x) = \phi(t)
\]</span></p></li>
</ol>
<p>In these expressions <span class="math inline">\(t = |x - x_0|/\lambda\)</span> and <span class="math inline">\(\phi(t)\)</span> is the standard Gaussian density function.</p>
<p><a href="#fig-kernel-funcs" class="quarto-xref">Figure&nbsp;<span>12.2</span></a> shows the kernel functions for <span class="math inline">\(\lambda=0.5\)</span> and <span class="math inline">\(\lambda=1\)</span>, respectively. The functions reach their maximum at <span class="math inline">\(|x-x_0| = 0\)</span> and decrease symmetrically in both directions. The Epanechnikov has a kink at <span class="math inline">\(|t| = \lambda\)</span> while the tricube kernel transitions smoothly through that point. Tricube kernels are sometimes preferred over the Epanechnikov kernel because the latter is not differentiable at <span class="math inline">\(|t|=1\)</span>. The Gaussian kernel is very smooth and for a given value of <span class="math inline">\(\lambda\)</span> assigns greater weights for points remote from <span class="math inline">\(x_0\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-kernel-funcs" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kernel-funcs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="reglocal_files/figure-html/fig-kernel-funcs-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2"><img src="reglocal_files/figure-html/fig-kernel-funcs-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kernel-funcs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Epanechnikov, tricube and Gaussian kernel functions popular in kernel regression and density estimation. Bandwidth set to 0.5 and 1 for each kernel.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In practice, the choice of the kernel function is less important than the choice of the bandwidth parameter <span class="math inline">\(\lambda\)</span>.</p>
<div class="example">
<div class="example-header">
<p>Example: Kernel Regression with Simulated Data</p>
</div>
<div class="example-container">
<p>The <code>ksmooth()</code> function in the <code>stats</code> package (built-in) can be used to compute the kernel regression smoother. <code>x.points=</code> specifies the points at which to evaluate the smoothed fit. <code>kernel="normal"</code> chooses the Gaussian kernel</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>kr_05 <span class="ot">&lt;-</span> <span class="fu">ksmooth</span>(X,Y,<span class="at">kernel=</span><span class="st">"normal"</span>,<span class="at">bandwidth=</span><span class="fl">0.5</span>, <span class="at">x.points=</span>xGrid)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>kr_09 <span class="ot">&lt;-</span> <span class="fu">ksmooth</span>(X,Y,<span class="at">kernel=</span><span class="st">"normal"</span>,<span class="at">bandwidth=</span><span class="fl">0.9</span>, <span class="at">x.points=</span>xGrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simdata-kernel-regression" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simdata-kernel-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="reglocal_files/figure-html/fig-simdata-kernel-regression-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simdata-kernel-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: Kernel regression estimates for Gaussian kernel with <span class="math inline">\(\lambda=0.5\)</span> and <span class="math inline">\(\lambda=0.9\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>Several noteworthy items in <a href="#fig-simdata-kernel-regression" class="quarto-xref">Figure&nbsp;<span>12.3</span></a>:</p>
<ul>
<li><p>The kernel regression estimate for <span class="math inline">\(\lambda=0.9\)</span> is more smooth than the estimate for <span class="math inline">\(\lambda=0.5\)</span>. A larger bandwidth widens the kernel (weight) function. As <span class="math inline">\(\lambda\)</span> increases the fit approaches a flat line at <span class="math inline">\(\widehat{\beta} = \overline{y}\)</span>, a global model.</p></li>
<li><p>In contrast to the <span class="math inline">\(k\)</span>-NN estimator, the kernel regression estimator is smooth. <span class="math inline">\(k\)</span>-NN estimates change abruptly when a point leaves the <span class="math inline">\(k\)</span>-neighborhood and another point enters. The <span class="math inline">\(k\)</span>-NN weight function <span class="math display">\[
K(x_0,x_i) = I(||x_i-x_0|| \le ||x_{(k)} - x_0 ||)
\]</span> is not smooth. The weight associated with a data point <span class="math inline">\(x_i\)</span> in kernel regression changes gradually with its distance from <span class="math inline">\(x_0\)</span>.</p></li>
<li><p>Fitting the model at <span class="math inline">\(x_0\)</span> and predicting at <span class="math inline">\(x_0\)</span> is the same operation; unlike in global models where you fit the model first, obtain the parameters, and then use them to predict at any point you choose.</p></li>
<li><p>There must be a variance-bias tradeoff between the bias of a model with large bandwidth and the variability of a model with small bandwidth. The hyperparameter <span class="math inline">\(\lambda\)</span> can be chosen by some form of cross-validation.</p></li>
<li><p>The kernel regression estimates generally capture the mean function well, but seem to struggle near the edges of the <span class="math inline">\(x\)</span>-range. Both underestimate the trend at the edge, the estimate with <span class="math inline">\(\lambda=0.5\)</span> turns away more sharply than the estimate with <span class="math inline">\(\lambda = 0.9\)</span>. The problem near the edge is that the estimator can use information only from one side of the edge. Fitting the model at <span class="math inline">\(x_0 = \max(x_i)\)</span> only observations with <span class="math inline">\(x &lt; x_0\)</span> are assigned non-zero weight. Unless the mean function is flat beyond the range of <span class="math inline">\(x\)</span>, the kernel estimator will be biased near the edges of the range.</p></li>
</ul>
</section>
<section id="cross-validation-for-lambda" class="level3">
<h3 class="anchored" data-anchor-id="cross-validation-for-lambda">Cross-validation for <span class="math inline">\(\lambda\)</span></h3>
<p>The best value for <span class="math inline">\(\lambda\)</span> that resolves the bias-variance tradeoff for a particular set of data can be determined by a form of cross-validation.</p>
<div class="example">
<div class="example-header">
<p>Example: Kernel Regression with Simulated Data</p>
</div>
<p>Here we implement a function that performs leave-one-out CV and computes the average squared prediction residual (PRESS). The function is then evaluated on a grid of candidate bandwidth values.</p>
<div class="example-container">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ksm.cv <span class="ot">&lt;-</span> <span class="cf">function</span>(X,Y,<span class="at">bw=</span><span class="fl">0.5</span>) {</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    MSTe <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">length</span>(bw))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">seq_along</span>(bw)) {</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        PRESS <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        ngood <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(X)) {</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>            nw <span class="ot">&lt;-</span> <span class="fu">ksmooth</span>(<span class="at">x        =</span>X[<span class="sc">-</span>i],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y        =</span>Y[<span class="sc">-</span>i],</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel   =</span><span class="st">"normal"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bandwidth=</span>bw[j],</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">x.points =</span>X[i])</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.na</span>(nw<span class="sc">$</span>y)){</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>                PRESS <span class="ot">&lt;-</span> PRESS <span class="sc">+</span> (Y[i] <span class="sc">-</span> nw<span class="sc">$</span>y)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>                ngood <span class="ot">&lt;-</span> ngood <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>            }</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        MSTe[j] <span class="ot">=</span> PRESS<span class="sc">/</span>ngood</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span> (<span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(bw,MSTe,ngood)))</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>bw_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.5</span>,<span class="fl">1.5</span>,<span class="fl">0.05</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>cvres <span class="ot">&lt;-</span> <span class="fu">ksm.cv</span>(X,Y,bw_grid)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Smallest LOOCV MSE "</span>, </span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    cvres<span class="sc">$</span>MSTe[<span class="fu">which.min</span>(cvres<span class="sc">$</span>MSTe)],</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">" at bandwidth "</span>,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    cvres<span class="sc">$</span>bw[<span class="fu">which.min</span>(cvres<span class="sc">$</span>MSTe)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Smallest LOOCV MSE  7.09627  at bandwidth  1.1</code></pre>
</div>
</div>
<p><a href="#fig-simdata-loocv-kr" class="quarto-xref">Figure&nbsp;<span>12.4</span></a> displays the LOOCV mean-squared error for bandwidth values from 0.5 to 1.5 in steps of 0.05. The smallest error is achieved at <span class="math inline">\(\lambda = 1.1\)</span>. <a href="#fig-simdata-kr-best" class="quarto-xref">Figure&nbsp;<span>12.5</span></a> displays the kernel regression estimate for that bandwidth. The local model fits the data well but continues to show bias at the boundary of the <span class="math inline">\(x\)</span>-range.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simdata-loocv-kr" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simdata-loocv-kr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="reglocal_files/figure-html/fig-simdata-loocv-kr-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simdata-loocv-kr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.4: Leave-one-out cross-validation MSE as a function of bandwidth.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simdata-kr-best" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simdata-kr-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="reglocal_files/figure-html/fig-simdata-kr-best-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simdata-kr-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.5: Kernel regression estimates at the cross-validated value of <span class="math inline">\(lambda=1.1\)</span> and true mean function.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you graph the results of cross-validation and the minimum criteria is achieved for the smallest (or largest) value of the hyperparameter being validated, you need to extend the grid of values below (or above) the values considered. Otherwise you might erroneously conclude that the “best” value is the value on the boundary of your candidate values. This is not a problem in <a href="#fig-simdata-loocv-kr" class="quarto-xref">Figure&nbsp;<span>12.4</span></a> where the minimum MSE does not fall on the boundary.</p>
</div>
</div>
</section>
</section>
<section id="local-regression" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="local-regression"><span class="header-section-number">12.2</span> Local Regression</h2>
<p>The kernel regression estimate at <span class="math inline">\(x_0\)</span> is equivalent to fitting a weighted intercept-only model <span class="math display">\[
Y(x) = \beta_0 + \epsilon
\]</span> where the weights are calculated according to a kernel function with some bandwidth <span class="math inline">\(\lambda\)</span>: <span class="math display">\[
w_i(x_0) = \frac{K_\lambda(x_0,x_i)}{\sum_{i=1}^n K_\lambda(x_0,x_i)}
\]</span></p>
<p>Local regression generalizes this idea to weighted polynomial regression models. A local regression model of degree 1 (linear) is a weighted regression with mean function <span class="math display">\[
Y(x) = \beta_0 + \beta_1 x + \epsilon
\]</span> A local regression model of degree 2 (quadratic) is a weighted regression with mean function <span class="math display">\[
Y(x) = \beta_0 + \beta_1 x + \beta_2 x^2 + \epsilon
\]</span> and so on. The kernel regression estimate of the previous section is a special case, a local regression model of degree 0.</p>
<p>The parameters in the local regression model change with prediction location <span class="math inline">\(x_0\)</span> because the kernel weight function changes with <span class="math inline">\(x_0\)</span>. Formally, the estimates at <span class="math inline">\(x_0\)</span> satisfy a weighted least squares criterion. For a model of degree 1 the criterion is</p>
<p><span class="math display">\[
            \mathop{\mathrm{arg\,min}}_{\beta_0(x_0), \beta_1(x_0)} = \sum_{i=1}^n K_\lambda(x_0,x_i) \left(y_i - \beta_0(x_0) - \beta_1(x_0) x_i \right )^2
\]</span></p>
<section id="choosing-the-degree" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-degree">Choosing the Degree</h3>
<p>The degree of a local regression polynomial is typically small, <span class="math inline">\(p=1\)</span> or <span class="math inline">\(p=2\)</span>. Higher-order polynomials are against the spirit of local methods that any function can be approximated in a small neighborhood by a low-order polynomials.</p>
<p>The boundary bias we noticed in the kernel regression (<span class="math inline">\(p=0\)</span>) estimates is greatly reduced when <span class="math inline">\(p &gt; 0\)</span>. The local model now depends on <span class="math inline">\(x\)</span> and does not approximate the mean with a flat line near the boundary.</p>
<p>For the same bandwidth, a quadratic model will be more flexible (wiggly) than a linear model. With curved trends, quadratic models can fit better than linear models in the interior of the <span class="math inline">\(x\)</span> range. This is a classical bias-variance tradeoff.</p>
<div class="example">
<div class="example-header">
<p>Example: Linear and Quadratic Local Polynomials with Simulated Data</p>
</div>
<div class="example-container">
<p>The <code>KernSmooth::locpoly</code> function in <code>R</code> computes local polynomial regression estimates with Gaussian kernels. For comparison purposes, the following fit models of degree 0, 1, and 2 for the same bandwidth.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(KernSmooth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>KernSmooth 2.23 loaded
Copyright M. P. Wand 1997-2009</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lp_05_0 <span class="ot">&lt;-</span> <span class="fu">locpoly</span>(X,Y,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">degree   =</span><span class="dv">0</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">kernel   =</span><span class="st">"normal"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bandwidth=</span><span class="fl">0.5</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">gridsize =</span><span class="dv">250</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">range.x  =</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">6</span>))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>lp_05_1 <span class="ot">&lt;-</span> <span class="fu">locpoly</span>(X,Y,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">degree   =</span><span class="dv">1</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">kernel   =</span><span class="st">"normal"</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bandwidth=</span><span class="fl">0.5</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">gridsize =</span><span class="dv">250</span>,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>                   <span class="at">range.x  =</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">6</span>))</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>lp_05_2 <span class="ot">&lt;-</span> <span class="fu">locpoly</span>(X,Y,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>                   <span class="at">degree   =</span><span class="dv">2</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">kernel   =</span><span class="st">"normal"</span>,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bandwidth=</span><span class="fl">0.5</span>,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>                   <span class="at">gridsize =</span><span class="dv">250</span>,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>                   <span class="at">range.x  =</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The local quadratic model is the most flexible at the same bandwidth (<a href="#fig-simdata-locpoly" class="quarto-xref">Figure&nbsp;<span>12.6</span></a>). All three estimates are similar in the interior of the <span class="math inline">\(x\)</span> range. The boundary bias of the linear and quadratic model is much reduced compared to the kernel regression (degree 0) estimate.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simdata-locpoly" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simdata-locpoly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="reglocal_files/figure-html/fig-simdata-locpoly-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simdata-locpoly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.6: Local polynomials of degree 0, 1, and 2 with Gaussian kernels and <span class="math inline">\(\lambda = 0.5\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="loess-regression" class="level3">
<h3 class="anchored" data-anchor-id="loess-regression">Loess Regression</h3>
<p>Loess (or LOESS) is a special case of local polynomial regression described by <span class="citation" data-cites="Cleveland1979">Cleveland (<a href="references.html#ref-Cleveland1979" role="doc-biblioref">1979</a>)</span>. The abbreviation stands for Local Estimated Scatterplot Smoothing. In terms of concepts introduced so far, Cleveland recommended a local linear model (degree 1) with a tricube kernel weight function and leave-one-out cross-validation to determine the bandwidth.</p>
<p>The tricube kernel was preferred because it reduces to exactly 0 and thus excludes observations outside of the tricube window from the calculations. The resulting computational savings were important at the time LOESS was proposed.</p>
<p>The <code>loess</code> function in <code>R</code> implements LOESS and specifies the bandwidth through a <code>span</code> parameter that determines the neighborhood of <span class="math inline">\(x_0\)</span> as a proportion of the data points. The tricube weight function is then applied to the points in the spanned neighborhood. By default <code>loess</code> fits quadratic models with <code>span=0.75</code>. This value is fairly large for applications where you want to model <span class="math inline">\(Y\)</span> as a function of <span class="math inline">\(X\)</span>, but works well in situations where you want to detect the presence of larger trends, as in the analysis of residuals.</p>
<p>Fitting of LOESS models and cross-validating the span parameter can be done conveniently in <code>R</code> with the <code>train</code> function in the <code>caret</code> package.</p>
<div class="example">
<div class="example-header">
<p>Example: LOESS Model of Degree 1 with Simulated Data</p>
</div>
<div class="example-container">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(Y,X))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(Y <span class="sc">~</span> X, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data    =</span>df,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">method  =</span><span class="st">"gamLoess"</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">tuneGrid=</span><span class="fu">expand.grid</span>(<span class="at">span =</span> <span class="fl">0.2</span>, <span class="at">degree=</span><span class="dv">1</span>), </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">trContro=</span><span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"none"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: gam</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: splines</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: foreach</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded gam 1.22-3</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simdata-loess_02" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simdata-loess_02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="reglocal_files/figure-html/fig-simdata-loess_02-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simdata-loess_02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.7: LOESS smooth with span 0.2, degree 1.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>To perform cross-validation for the span parameter, you can supply instructions to the <code>train</code> function. The <code>tuneGrid</code> parameter provides a data frame with values for the hyperparameters. In the code below, the span is varied from 0.15 to 0.75 in 40 steps and the degree of the local polynomial is held fixed at 1. The <code>trControl</code> parameter defines the behavior of the <code>train</code> function. Here, 10-fold cross-validatoin of the hyperparameters is requested.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3678</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">span =</span> <span class="fu">seq</span>(<span class="fl">0.15</span>, <span class="fl">0.75</span>, <span class="at">len =</span> <span class="dv">40</span>), <span class="at">degree =</span> <span class="dv">1</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">train</span>(Y <span class="sc">~</span> X, </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">data     =</span>df, </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">method   =</span><span class="st">"gamLoess"</span>, </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">tuneGrid =</span>grid, </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl=</span>ctrl)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Additive Model using LOESS 

100 samples
  1 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 89, 89, 90, 92, 91, 90, ... 
Resampling results across tuning parameters:

  span       RMSE      Rsquared   MAE     
  0.1500000  2.901927  0.7325910  2.145192
  0.1653846  2.919378  0.7336561  2.140403
  0.1807692  2.615121  0.7373488  2.036346
  0.1961538  2.624746  0.7364527  2.030095
  0.2115385  2.656667  0.7304098  2.042989
  0.2269231  2.668584  0.7263728  2.058201
  0.2423077  2.679732  0.7206956  2.064964
  0.2576923  2.694870  0.7175513  2.077081
  0.2730769  2.757301  0.7032400  2.107686
  0.2884615  2.787906  0.6907119  2.117425
  0.3038462  2.811633  0.6848968  2.142258
  0.3192308  2.831422  0.6761193  2.170968
  0.3346154  2.885184  0.6611100  2.218675
  0.3500000  2.967564  0.6400800  2.275226
  0.3653846  3.004447  0.6280659  2.305204
  0.3807692  3.066032  0.6113772  2.340453
  0.3961538  3.097985  0.6022572  2.362501
  0.4115385  3.163806  0.5835644  2.402466
  0.4269231  3.203701  0.5713253  2.422956
  0.4423077  3.257056  0.5567435  2.457546
  0.4576923  3.292731  0.5471882  2.476899
  0.4730769  3.338219  0.5342448  2.504264
  0.4884615  3.351780  0.5291961  2.515220
  0.5038462  3.391540  0.5169620  2.539841
  0.5192308  3.443358  0.5013535  2.572879
  0.5346154  3.478873  0.4891299  2.597151
  0.5500000  3.501811  0.4799188  2.620423
  0.5653846  3.536125  0.4668376  2.645889
  0.5807692  3.592910  0.4487972  2.679671
  0.5961538  3.645415  0.4337016  2.712018
  0.6115385  3.605952  0.4463734  2.686381
  0.6269231  3.574397  0.4561588  2.666609
  0.6423077  3.623664  0.4421608  2.695329
  0.6576923  3.605723  0.4552149  2.666462
  0.6730769  3.632124  0.4461638  2.684623
  0.6884615  3.650800  0.4401234  2.699304
  0.7038462  3.667380  0.4341022  2.713919
  0.7192308  3.690093  0.4270565  2.732718
  0.7346154  3.710603  0.4196154  2.752871
  0.7500000  3.743538  0.4038491  2.785017

Tuning parameter 'degree' was held constant at a value of 1
RMSE was used to select the optimal model using the smallest value.
The final values used for the model were span = 0.1807692 and degree = 1.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reglocal_files/figure-html/loess_k_10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(model<span class="sc">$</span>results<span class="sc">$</span>RMSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.615121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model<span class="sc">$</span>results<span class="sc">$</span>span[<span class="fu">which.min</span>(model<span class="sc">$</span>results<span class="sc">$</span>RMSE)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1807692</code></pre>
</div>
</div>
<p>The smallest root mean square error (RMSE) of 2.6151 is achieved with a span of 0.1808.</p>
</section>
</section>
<section id="sec-basis-functions" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="sec-basis-functions"><span class="header-section-number">12.3</span> Basis Functions</h2>
<section id="segments-knots-and-constraints" class="level3">
<h3 class="anchored" data-anchor-id="segments-knots-and-constraints">Segments, Knots, and Constraints</h3>
<p>Local models using weight functions provide a lot of flexibility to model smooth functions based on a simple idea: if a constant, linear, or quadratic model approximates the local behavior at <span class="math inline">\(x_0\)</span> well then we can estimate the parameters of that local model through a weighted analysis that downweighs observations based on their distance from <span class="math inline">\(x_0\)</span>. Data points that are far from <span class="math inline">\(x_0\)</span> will not have much impact on determining the local behavior if we choose the bandwidth of the kernel weight function properly.</p>
<p>Greater flexibility in the fitted model could also be achieved by adding higher-order polynomial terms and fitting a global model. Unfortunately, this does not work well. Adding a higher-order term such as a cubic (<span class="math inline">\(x^3\)</span>), quartic (<span class="math inline">\(x^4\)</span>), or quintic (<span class="math inline">\(x^5\)</span>) term to pick up curvature in one region can introduce strange behavior in another region. <a href="#fig-quintic-model" class="quarto-xref">Figure&nbsp;<span>12.8</span></a> shows the fit of global polynomial models with up to third, fourth, and fifth degree terms for the simulated data. The quartic model <span class="math display">\[
Y = \beta_0 + \beta_1x + \beta_2x^2 + \beta_3x^3 + \beta_4 x^4 + \epsilon
\]</span> does a pretty good job in capturing the curvature in the center of the <span class="math inline">\(x\)</span> range. It could benefit from more flexibility in the upper region of <span class="math inline">\(x\)</span>, though. Adding a quintic term <span class="math inline">\(\beta_5 x^5\)</span> to the model improves the fit for larger values of <span class="math inline">\(x\)</span> but leads to poor behavior for small values of <span class="math inline">\(x\)</span>.</p>
<div id="fig-quintic-model" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-quintic-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/QuinticPolynomials.png" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="quarto-lightbox-gallery-3"><img src="images/QuinticPolynomials.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-quintic-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.8: Polynomial models up to the 5<sup>th</sup> degree.
</figcaption>
</figure>
</div>
<p>Can we introduce flexibility into the model by creating local behavior and avoid the uncontrolled behavior of higher-degree polynomials? The answer is “yes”, and <strong>splines</strong> is the way we achieve that.</p>
<p>A spline model is a <strong>piecewise</strong> polynomial model. Rather than fitting a local model at every prediction point, a spline model connects polynomial models at specific points along the <span class="math inline">\(x\)</span>-axis, called <strong>knots</strong>. As with global models, fitting a spline model and making predictions are separate steps. The model is local in the sense that we have different polynomials in different sections of the <span class="math inline">\(x\)</span> range. <a href="#fig-piecewise-linear" class="quarto-xref">Figure&nbsp;<span>12.9</span></a> displays the concept for piecewise polynomials of degree 1–that is, piecewise linear models. The extreme points of the <span class="math inline">\(x\)</span> range serve as the boundary knots, four interior knots are evenly spaced along the <span class="math inline">\(x\)</span> axis. This results in five linear segments. If we denote the interior knots as <span class="math inline">\(c_1, \cdots, c_4\)</span>, this piecewise linear model can be written as follows</p>
<p><span class="math display">\[
Y = \left \{ \begin{array}{ll} \beta_{01} + \beta_{11} x &amp; x \le c_1 \\
\beta_{02} + \beta_{12}x &amp; c_1 &lt; x \le c_2 \\
\beta_{03} + \beta_{13}x &amp; c_2 &lt; x \le c_3 \\
\beta_{04} + \beta_{14}x &amp; c_3 &lt; x \le c_4 \\
\beta_{05} + \beta_{15}x &amp; x &gt; c_4 \\
\end{array}
\right .
\]</span></p>
<p>Each segment has a separate intercept and slope estimate. As the number of knots increases, the model becomes more localized and has more parameters.</p>
<div id="fig-piecewise-linear" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-piecewise-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/PiecewiseLinear.png" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="quarto-lightbox-gallery-4"><img src="images/PiecewiseLinear.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-piecewise-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.9: Piecewise linear model with four interior knots.
</figcaption>
</figure>
</div>
<p>The name spline originates in construction where thin strips of wood were used to create curved shapes, for example, in shipbuilding. The strips of wood, called splines, are fixed at two points with devices called “dogs” or “ducks” and can be flexed between them (<a href="#fig-spline-construction" class="quarto-xref">Figure&nbsp;<span>12.10</span></a>).</p>
<div id="fig-spline-construction" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spline-construction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Spline.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spline-construction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.10: A spline in construction. <a href="https://www.lancaster.ac.uk/stor-i-student-sites/tamas-papp/2020/02/10/splines/">Source</a>
</figcaption>
</figure>
</div>
<p>The segments in <a href="#fig-piecewise-linear" class="quarto-xref">Figure&nbsp;<span>12.9</span></a> are not curved, that can be fixed by increasing the degree of the polynomial in each segment. But we recognize another problem with the piecewise linear model, the fitted lines do not connect at the segments. In order for the model to be continuous across the interior knots, the parameter estimates cannot be chosen freely–they have to obey certain constraints. For example, in order for the first two segments in <a href="#fig-piecewise-linear" class="quarto-xref">Figure&nbsp;<span>12.9</span></a> to connect, we need to have <span class="math display">\[
\beta_{01} + \beta_{11} c_1 = \beta_{02} + \beta_{12} c_1
\]</span></p>
<p>We would not be satisfied with the segments just touching at the knots, we also would want the spline to transition smoothly through the knots. So we can impose additional constraints on the polynomials. To ensure that the segments have the same slope at the knot we constrain their first derivative <span class="math display">\[
\beta_{11} = \beta_{12}
\]</span></p>
<p>With each constraint the number of free parameters in the model is reduced. We started with ten parameters in the model with four (interior) knots and disconnected lines (<a href="#fig-piecewise-linear" class="quarto-xref">Figure&nbsp;<span>12.9</span></a>). Imposing continuity at each knot imposes one constraint at each knot, leaving us with 6 free parameters (we are using 6 degrees of freedom for the model). Imposing continuity in the first derivative at each knot removes another 4 parameters, leaving us with 2 degrees of freedom. Without increasing the degree of the polynomial we will not be able to add further constraints. In fact, the continuous piecewise linear model with continuity in the first derivatives is just a global simple linear regression model.</p>
<p>To leave degrees of freedom to pick up local trends in the mean function we use cubic splines that are continuous at the knots and have the same first and second derivatives to be equal at the knots. A spline that satisfies those conditions is known as a cubic spline (<a href="#fig-cubic-spline" class="quarto-xref">Figure&nbsp;<span>12.11</span></a>) or a degree-3 spline.</p>
<p>A spline of degree <span class="math inline">\(d\)</span> in general is a piecewise polynomial of degree <span class="math inline">\(d\)</span> with continuity constraints in the derivatives up to degree <span class="math inline">\(d-1\)</span> at each knot. There is typically no need to engage splines of higher orders than cubic splines. They still have a discontinuity at the knots since they are continuous only up to second derivatives but it is said that the discontinuity is not visible to the human eye <span class="citation" data-cites="hastie_ESL">(<a href="references.html#ref-hastie_ESL" role="doc-biblioref">Hastie, Tibshirani, and Friedman 2001, 134</a>)</span>.</p>
<div id="fig-cubic-spline" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cubic-spline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/CubicSpline.png" class="lightbox" data-glightbox="description: .lightbox-desc-5" data-gallery="quarto-lightbox-gallery-5"><img src="images/CubicSpline.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cubic-spline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.11: Cubic spline with four interior knots.
</figcaption>
</figure>
</div>
<p>We also want to handle the boundary properly and are imposing another constraint: the model should have degree 1 beyond the range of <span class="math inline">\(x\)</span> in the training data. This is known as a <strong>natural cubic spline</strong> (<a href="#fig-natural-cubic-spline" class="quarto-xref">Figure&nbsp;<span>12.12</span></a>). The natural cubic spline achieves linearity at the boundary by imposing additional constraints, two at each boundary knot. The four degrees of freedom made available–compared to the cubic spline–can be used to place an additional interior knot.</p>
<div id="fig-natural-cubic-spline" class="lightbox quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-natural-cubic-spline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/NaturalCubicSpline.png" class="lightbox" data-glightbox="description: .lightbox-desc-6" data-gallery="quarto-lightbox-gallery-6"><img src="images/NaturalCubicSpline.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-natural-cubic-spline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.12: Natural cubic spline with four interior knots.
</figcaption>
</figure>
</div>
<p>More degrees of freedom in the spline translates into more free parameters and more flexibility in the fit. For a cubic spline with <span class="math inline">\(K\)</span> knots, there are <span class="math inline">\(K+1\)</span> degree-3 polynomial segments that obey <span class="math inline">\(K\times 3\)</span> constraints at the knots. The model thus uses <span class="math inline">\(4(K+1) - 3K = K+4\)</span> degrees of freedom. The flexibility of a spline model increases with the number of knots.</p>
</section>
<section id="basis-function-representation" class="level3">
<h3 class="anchored" data-anchor-id="basis-function-representation">Basis Function Representation</h3>
<p>Fitting a spline model is a constrained optimization problem: minimize the residual sum of squares of the piecewise polynomial subject to the continuity constraints imposed on the parameters. There is a more direct way in which the model is written in a way that incorporates the constraints and a standard least-squares routine for linear models can be used.</p>
<p>Let’s think of our model in a slightly different formulation, <span class="math display">\[
Y = \beta_0 + \beta_1 h_1(x) + \beta_2 h_2(x) + \cdots + \beta_p h_p(x) + \epsilon
\]</span> The functions <span class="math inline">\(h_1(x), \cdots, h_p(x)\)</span> are known transformations of <span class="math inline">\(x\)</span>. For example, a third-degree polynomial has <span class="math inline">\(h_1(x)=x\)</span>, <span class="math inline">\(h_2(x)=x^2\)</span>, and <span class="math inline">\(h_3(x)=x^3\)</span>.</p>
<p>This is called the <strong>basis function</strong> representation of the linear model. The cubic spline model can be written as a third-degree polynomial augmented by <strong>truncated power basis functions</strong>. A truncated power basis function takes the general form</p>
<p><span class="math display">\[
t^n_+ = \left \{ \begin{array}{cc} t^n &amp; t &gt; 0 \\ 0 &amp; t \le 0\end{array}\right .
\]</span></p>
<p>The cubic spline model with <span class="math inline">\(K\)</span> (interior) knots, written in terms of truncated power basis functions becomes <span id="eq-cubic-spline-tpf"><span class="math display">\[
Y = \beta_0 + \beta_1 x + \beta_2 x^2 + \beta_3 x^3 + \beta_{3+1}(x-c_1)^3_+ + \cdots + \beta_{3+K}(x-c_K)^3_+ + \epsilon
\tag{12.1}\]</span></span></p>
<p>For each knot, an input variable is added, its values are the 3-rd order truncated power basis functions of the distance from the <span class="math inline">\(k\)</span><sup>th</sup> knot. The model has <span class="math inline">\(K+4\)</span> parameters, as expected for a cubic spline.</p>
<div class="example">
<div class="example-header">
<p>Example: Cubic Spline with 3 Knots</p>
</div>
<div class="example-container">
<p>For the simulated data we can fit a cubic spline with 3 knots by constructing a model matrix for <a href="#eq-cubic-spline-tpf" class="quarto-xref">Equation&nbsp;<span>12.1</span></a> and passing it to the <code>lm.fit</code> function. First we need to decide on the placement of the three knots. One option is to place knots evenly throughout the range of <span class="math inline">\(x\)</span>. Or, we can place knots at certain percentiles of the distribution of the <span class="math inline">\(x\)</span> data. We choose the 1st, 2nd (median), and 3rd quartile here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">summary</span>(X)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>c_1 <span class="ot">&lt;-</span> s[<span class="dv">2</span>] <span class="co"># 1st. quartile</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>c_2 <span class="ot">&lt;-</span> s[<span class="dv">3</span>] <span class="co"># median</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>c_3 <span class="ot">&lt;-</span> s[<span class="dv">5</span>] <span class="co"># 3rd quartile</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>c_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1st Qu. 
-1.025803 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>c_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Median 
0.05192918 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>c_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3rd Qu. 
1.39678 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>tpf <span class="ot">&lt;-</span> <span class="cf">function</span>(x,knot,degree) {</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    t <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(x <span class="sc">&gt;</span> knot, (x<span class="sc">-</span>knot)<span class="sc">^</span>degree, <span class="dv">0</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>Xmatrix <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">length</span>(X)), X, X<span class="sc">^</span><span class="dv">2</span>, X<span class="sc">^</span><span class="dv">3</span>, </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">tpf</span>(X,c_1,<span class="dv">3</span>), <span class="fu">tpf</span>(X,c_2,<span class="dv">3</span>), <span class="fu">tpf</span>(X,c_3,<span class="dv">3</span>))</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(Xmatrix) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Inctpt"</span>,<span class="st">"x"</span>,<span class="st">"x^2"</span>,<span class="st">"x^3"</span>,<span class="st">"tpf_c1"</span>,<span class="st">"tpf_c2"</span>,<span class="st">"tpf_c3"</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(Xmatrix[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,],<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Inctpt       x    x^2      x^3  tpf_c1  tpf_c2 tpf_c3
 [1,]      1  0.4479 0.2006   0.0898  3.2003  0.0621 0.0000
 [2,]      1 -2.3124 5.3474 -12.3656  0.0000  0.0000 0.0000
 [3,]      1  0.8448 0.7137   0.6030  6.5459  0.4985 0.0000
 [4,]      1 -2.6495 7.0199 -18.5993  0.0000  0.0000 0.0000
 [5,]      1  0.2822 0.0796   0.0225  2.2377  0.0122 0.0000
 [6,]      1 -1.0721 1.1494  -1.2323  0.0000  0.0000 0.0000
 [7,]      1 -0.6232 0.3884  -0.2421  0.0653  0.0000 0.0000
 [8,]      1  3.1122 9.6859  30.1447 70.8563 28.6608 5.0481
 [9,]      1 -0.8961 0.8029  -0.7195  0.0022  0.0000 0.0000
[10,]      1  0.6422 0.4125   0.2649  4.6412  0.2057 0.0000</code></pre>
</div>
</div>
<p>Observations to the left of <span class="math inline">\(c_1\)</span> = -1.0258 do not receive a contribution from the augmented power function terms, for example the second observation. Observation #8, which falls to the right of <span class="math inline">\(c_3\)</span> = 1.3968 receives a contribution from all three truncated power function terms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cub_spline <span class="ot">&lt;-</span> <span class="fu">lm.fit</span>(<span class="at">x=</span>Xmatrix,<span class="at">y=</span>Y)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>cub_spline<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Inctpt          x        x^2        x^3     tpf_c1     tpf_c2     tpf_c3 
 -4.324405 -11.263153  -6.970494  -0.951829   3.572409  -5.185659   4.441695 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simdata-cubspline" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simdata-cubspline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="reglocal_files/figure-html/fig-simdata-cubspline-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simdata-cubspline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.13: Cubic spline fit by linear least squares based on truncated power basis functions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For a model with only seven parameters the cubic spline with knots at the 1st, 2nd, and 3rd quartile provides an excellent fit (<a href="#fig-simdata-cubspline" class="quarto-xref">Figure&nbsp;<span>12.13</span></a>)</p>
</div>
</div>
</section>
<section id="regression-splines" class="level3">
<h3 class="anchored" data-anchor-id="regression-splines">Regression Splines</h3>
<p>The model in the previous example is known as a <strong>regression spline</strong>, characterized by placing a fixed number of knots. A common approach is to specify <span class="math inline">\(K\)</span>, the number of knots and placing knots at percentiles of the <span class="math inline">\(x\)</span> values, as in the previous example. Another option is to place more knots in regions where the mean function is expected to vary more.</p>
<p>The truncated power basis function is one approach to generating the <span class="math inline">\(\textbf{X}\)</span> matrix for a least-squares regression that produces a particular spline. It is not the numerically most advantageous approach. There are many equivalent basis functions to represent polynomials. A popular basis are the B-spline basis functions.</p>
<p>The <code>R</code> functions <code>bs()</code> and <code>ns()</code> in the <code>splines</code> library compute cubic spline matrices and natural cubic spline matrices based on B-splines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>xx <span class="ot">&lt;-</span> <span class="fu">bs</span>(X,<span class="at">df=</span><span class="dv">6</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(xx,<span class="st">"knots"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.02580300  0.05192918  1.39678037</code></pre>
</div>
</div>
<p>The number of knots generated by <code>bs()</code> equals the chosen degrees of freedom minus the degree of the spline, which is 3 by default. The knots are placed at percentiles of <span class="math inline">\(x\)</span>, a third-order spline with 6 degrees of freedom results in 3 knots at the 1st, 2nd, and 3rd quartiles; the same values used earlier in the truncated power function example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(xx[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,],<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            1       2       3       4       5       6
 [1,] 0.00000 0.04647 0.76826 0.18360 0.00167 0.00000
 [2,] 0.40941 0.43423 0.09265 0.00000 0.00000 0.00000
 [3,] 0.00000 0.00914 0.66063 0.31682 0.01340 0.00000
 [4,] 0.47892 0.34084 0.05217 0.00000 0.00000 0.00000
 [5,] 0.00000 0.07531 0.79106 0.13331 0.00033 0.00000
 [6,] 0.07129 0.51921 0.40950 0.00000 0.00000 0.00000
 [7,] 0.01545 0.38341 0.59720 0.00394 0.00000 0.00000
 [8,] 0.00000 0.00000 0.08153 0.39302 0.44131 0.08414
 [9,] 0.04277 0.47603 0.48107 0.00013 0.00000 0.00000
[10,] 0.00000 0.02336 0.72313 0.24798 0.00553 0.00000</code></pre>
</div>
</div>
<p>Although the <code>xx</code> matrix produced by <code>bs()</code> is not identical to the <code>Xmatrix</code> based on the truncated power basis functions, the models are equivalent and the predicted values are identical. The conditioning of the <span class="math inline">\(\textbf{X}^\prime\textbf{X}\)</span> matrix based on the truncated power basis is poorer than the conditioning of the <span class="math inline">\(\textbf{X}^\prime\textbf{X}\)</span> matrix computed from the B-spline basis. The pairwise correlations are generally higher in the former.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(Xmatrix[,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]),<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             x     x^2     x^3  tpf_c1  tpf_c2  tpf_c3
x      1.00000 0.20112 0.82204 0.71892 0.63024 0.50541
x^2    0.20112 1.00000 0.42635 0.76803 0.77741 0.73487
x^3    0.82204 0.42635 1.00000 0.89977 0.88997 0.84555
tpf_c1 0.71892 0.76803 0.89977 1.00000 0.98705 0.92475
tpf_c2 0.63024 0.77741 0.88997 0.98705 1.00000 0.97202
tpf_c3 0.50541 0.73487 0.84555 0.92475 0.97202 1.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(xx),<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1        2        3        4        5        6
1  1.00000  0.46034 -0.59238 -0.49291 -0.29365 -0.13162
2  0.46034  1.00000 -0.08910 -0.75758 -0.48386 -0.21712
3 -0.59238 -0.08910  1.00000 -0.00750 -0.45067 -0.30818
4 -0.49291 -0.75758 -0.00750  1.00000  0.59160 -0.05045
5 -0.29365 -0.48386 -0.45067  0.59160  1.00000  0.28366
6 -0.13162 -0.21712 -0.30818 -0.05045  0.28366  1.00000</code></pre>
</div>
</div>
<p>The function <code>ns()</code> produces the natural cubic splines from the B-spline basis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>nn <span class="ot">&lt;-</span> <span class="fu">ns</span>(X,<span class="at">df=</span><span class="dv">6</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(nn[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,],<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            1       2       3        4       5        6
 [1,] 0.01539 0.53224 0.44483  0.00664 0.00211 -0.00122
 [2,] 0.24048 0.00000 0.00000 -0.20417 0.48178 -0.27761
 [3,] 0.00000 0.24623 0.69323  0.05335 0.01697 -0.00978
 [4,] 0.13541 0.00000 0.00000 -0.20501 0.48376 -0.27875
 [5,] 0.04383 0.63577 0.31891  0.00131 0.00042 -0.00024
 [6,] 0.68611 0.15236 0.00000 -0.05195 0.12258 -0.07063
 [7,] 0.54971 0.41216 0.00251 -0.01149 0.02711 -0.01562
 [8,] 0.00000 0.00000 0.13784  0.50699 0.26615  0.08901
 [9,] 0.66500 0.23641 0.00000 -0.03179 0.07502 -0.04323
[10,] 0.00205 0.38855 0.58442  0.02201 0.00700 -0.00404</code></pre>
</div>
</div>
<p>The models can be fit without first generating the spline matrix:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ns_spline <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">ns</span>(X,<span class="at">df=</span><span class="dv">6</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>bs_spline <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">bs</span>(X,<span class="at">df=</span><span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-simdata-bs-ns" class="quarto-xref">Figure&nbsp;<span>12.14</span></a> displays the fitted values for the 6-df cubic and natural cubic splines.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simdata-bs-ns" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simdata-bs-ns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="reglocal_files/figure-html/fig-simdata-bs-ns-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-7" data-gallery="quarto-lightbox-gallery-7"><img src="reglocal_files/figure-html/fig-simdata-bs-ns-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simdata-bs-ns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.14: Cubic and natural cubic splines with 6 degrees of freedom.
</figcaption>
</figure>
</div>
</div>
</div>
<p>An objective method for choosing the number of knots in regression splines is through cross-validation.</p>
<div class="example">
<div class="example-header">
<p>Example: Choosing Degrees of Freedom by Cross-validation</p>
</div>
<div class="example-container">
<p>The following code use the <code>caret::train</code> function in <code>R</code> to choose the degrees of freedom of the cubic spline based on 10-fold cross-validation. The degrees of freedom evaluated range from 2 to 20.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Y=</span>Y,<span class="at">X=</span>X)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3678</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">df =</span> <span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">20</span>,<span class="at">by=</span><span class="dv">1</span>))</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">train</span>(Y <span class="sc">~</span> X, </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">data      =</span> df, </span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">method    =</span> <span class="st">"gamSpline"</span>, </span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">tuneGrid  =</span> grid, </span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl =</span> ctrl)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Additive Model using Splines 

100 samples
  1 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 89, 89, 90, 92, 91, 90, ... 
Resampling results across tuning parameters:

  df  RMSE      Rsquared   MAE     
   2  4.044198  0.3076557  3.020568
   3  3.659884  0.4245450  2.749611
   4  3.304364  0.5299490  2.565251
   5  2.989824  0.6241050  2.373329
   6  2.749716  0.6861406  2.208537
   7  2.589525  0.7207527  2.094446
   8  2.489518  0.7400459  2.028971
   9  2.427930  0.7516088  1.999040
  10  2.389342  0.7591292  1.983502
  11  2.364524  0.7643125  1.973074
  12  2.348485  0.7679405  1.965031
  13  2.338639  0.7703677  1.959352
  14  2.333664  0.7717649  1.955700
  15  2.332962  0.7722239  1.955451
  16  2.336070  0.7718901  1.957769
  17  2.343017  0.7708601  1.961188
  18  2.353694  0.7692620  1.965484
  19  2.368154  0.7672486  1.973497
  20  2.386424  0.7648974  1.982863

RMSE was used to select the optimal model using the smallest value.
The final value used for the model was df = 15.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reglocal_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The square root of the mean square error (RMSE) achieves a minimum for <code>df=15</code> although any value between 12 and 17 is reasonable.</p>
<p>Next, the final model is trained using the degrees of freedom chosen by cross-validation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">train</span>(Y <span class="sc">~</span> X, </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data      =</span> df, </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">method    =</span> <span class="st">"gamSpline"</span>, </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">tuneGrid  =</span> <span class="fu">expand.grid</span>(<span class="at">df=</span>model<span class="sc">$</span>bestTune<span class="sc">$</span>df), </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"none"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reglocal_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Cross-validated cubic spline fit.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-smoothing-splines" class="level3">
<h3 class="anchored" data-anchor-id="sec-smoothing-splines">Smoothing Splines</h3>
<p>Regression splines require specification of the number of knots <span class="math inline">\(K\)</span> and their placement <span class="math inline">\(c_1, \cdots, c_K\)</span>. Equivalently, the degrees of freedom of the spline can be specified instead of <span class="math inline">\(K\)</span>. Choosing <span class="math inline">\(K\)</span> too small results in bias and choosing <span class="math inline">\(K\)</span> too large leads to overfit models with high variance.</p>
<p>Smoothing splines approach the issue of knot placement from a different angle. Why not place knots at all unique values of <span class="math inline">\(X\)</span>? This creates a high-dimensional problem that can be adjusted through <strong>regularization</strong>. This resolves the questions of knot number and knot placement and shifts attention from cross-validating <span class="math inline">\(K\)</span> to choosing the regularization parameter.</p>
<p>The regularization penalty for smoothing splines is <span class="math display">\[
   \lambda \int f^{\prime\prime}(v)\,dv  
\]</span> where <span class="math inline">\(f^{\prime\prime}\)</span> denotes the second derivative of the mean function and <span class="math inline">\(\lambda\)</span> is the hyperparameter. The rationale for this penalty term is as follows: the second derivative <span class="math inline">\(f^{\prime\prime}(x)\)</span> measures the curvature of <span class="math inline">\(f\)</span> at <span class="math inline">\(x\)</span>. High absolute values indicate that <span class="math inline">\(f\)</span> changes quickly in the neighborhood of <span class="math inline">\(x\)</span>, the sign of a wiggly function. The integral of the second derivative can be interpreted as the degree of wiggliness across the range of <span class="math inline">\(x\)</span>.</p>
<p>For a given value of <span class="math inline">\(\lambda\)</span> more wiggly functions result in a higher penalty. For <span class="math inline">\(\lambda = 0\)</span> no penalty is added. The basic model for a smoothing spline is a cubic spline with knots at all unique <span class="math inline">\(x\)</span>-values. The regularization penalty shrinks the coefficient estimates of the spline and reduces the variability of the fitted function this way.</p>
<p>An interesting aspect are the <strong>effective</strong> or <strong>equivalent degrees of freedom</strong>. The smoothing spline has <span class="math inline">\(n\)</span> parameters but these are shrunk if the penalty term kicks in. The equivalent degrees of freedom are a measure of the flexibility of the fitted function. Mathematically, the fitted values of a smoothing spline is a linear function of the observed data. For each value <span class="math inline">\(\lambda\)</span>, the solution can be written as</p>
<p><span class="math display">\[
\widehat{y}_\lambda = \textbf{S}_\lambda \textbf{y}
\]</span> where <span class="math inline">\(\textbf{S}_\lambda\)</span> is the <strong>smoother matrix</strong>, akin to the Hat matrix in global regression models. Recall that the Hat matrix is an orthogonal projection matrix and its trace equals the number of parameters (the degrees of freedom) of the model. Similarly, the equivalent degrees of freedom of a smoother are obtained as the trace of the smoother matrix, <span class="math display">\[
df_\lambda = tr(\textbf{S}_\lambda) = \sum_{i=1}^n S[ii]_\lambda
\]</span></p>
<div class="example">
<div class="example-header">
<p>Example: Apple Share Prices</p>
</div>
<div class="example-container">
<p>The data for this example are the weekly closing share prices of Apple (ticker symbol AAPL) between January 1996 and January 2024. <a href="#fig-aapl-share-price" class="quarto-xref">Figure&nbsp;<span>12.15</span></a> shows a time series of these prices along with the dates major Apple products were introduced.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"duckdb"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: DBI</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(<span class="fu">duckdb</span>(),<span class="at">dbdir =</span> <span class="st">"ads.ddb"</span>,<span class="at">read_only=</span><span class="cn">TRUE</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>weekly <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="st">"SELECT * FROM AAPLWeekly"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>weekly<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">make_date</span>(weekly<span class="sc">$</span>year,weekly<span class="sc">$</span>month,weekly<span class="sc">$</span>day)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dbDisconnect</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-aapl-share-price" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aapl-share-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="reglocal_files/figure-html/fig-aapl-share-price-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-8" data-gallery="quarto-lightbox-gallery-8"><img src="reglocal_files/figure-html/fig-aapl-share-price-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aapl-share-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.15: Weekly AAPL close share prices from January 1996 until January 2024 and dates major products were introduced.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>smooth.spline</code> function in <code>R</code> computes smoothing splines and selects the smoothing parameter (the penalty hyperparameter) by leave-one-out cross-validation. It should be noted that <code>smooth.spline</code> by default does <strong>not</strong> place knots at all unique <span class="math inline">\(x\)</span> values, but places evenly-spaced knots, their number is a function of the unique number of <span class="math inline">\(x\)</span>-values. You can change this behavior by setting <code>all.knots=TRUE</code>.</p>
<p>In the AAPL example, there are 1,461 unique dates, and <code>smooth.spline</code> would choose 154 knots by default.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># general method for computing the number of unique values in a numeric vector</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>nx <span class="ot">&lt;-</span> <span class="fu">length</span>(weekly<span class="sc">$</span>date) <span class="sc">-</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(<span class="fu">duplicated</span>(<span class="fu">round</span>((weekly<span class="sc">$</span>date <span class="sc">-</span> <span class="fu">mean</span>(weekly<span class="sc">$</span>date))<span class="sc">/</span><span class="fl">1e-6</span>)))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>nx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1461</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.nknots.smspl</span>(nx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>smspl_a <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(<span class="at">y=</span>weekly<span class="sc">$</span>Close,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">x=</span>weekly<span class="sc">$</span>date,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">all.knots=</span><span class="cn">TRUE</span>,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">cv=</span><span class="cn">TRUE</span>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>smspl_a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
smooth.spline(x = weekly$date, y = weekly$Close, cv = TRUE, all.knots = TRUE)

Smoothing Parameter  spar= 0.3941696  lambda= 1.661548e-10 (11 iterations)
Equivalent Degrees of Freedom (Df): 607.3517
Penalized Criterion (RSS): 1235.319
PRESS(l.o.o. CV): 2.544907</code></pre>
</div>
</div>
<p>The cross-validation leads to a PRESS criterion of 2.5449 and equivalent degrees of freedom of 607.352. The regularization penalized the spline from 1461 interior knots to the equivalent of a spline with about 610 knots. The smoothing parameter <code>spar</code> has a substantial value of 0.3942.</p>
<p>Setting <code>all.knots=FALSE</code> leads to the following analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>smspl_s <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(<span class="at">y=</span>weekly<span class="sc">$</span>Close,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">x=</span>weekly<span class="sc">$</span>date,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">all.knots=</span><span class="cn">FALSE</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">cv=</span><span class="cn">TRUE</span>)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>smspl_s</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
smooth.spline(x = weekly$date, y = weekly$Close, cv = TRUE, all.knots = FALSE)

Smoothing Parameter  spar= 0.007723702  lambda= 2.115138e-09 (15 iterations)
Equivalent Degrees of Freedom (Df): 152.8225
Penalized Criterion (RSS): 8154.007
PRESS(l.o.o. CV): 6.96885</code></pre>
</div>
</div>
<p>The smoothing parameter is much smaller, <code>spar</code>=0.00772 and the equivalent degrees of freedom are not much different from the number of knots used (154). This suggests that this smoothing spline has not been penalized sufficiently, the appropriate number of equivalent degrees of freedom is higher–this was confirmed in the first call to <code>smooth.spline</code> with <code>all.knots=TRUE</code>. Also note that the PRESS statistic for this run is almost 3 times higher than in the first analysis.</p>
<p><a href="#fig-aapl-smooth-splines" class="quarto-xref">Figure&nbsp;<span>12.16</span></a> compares the fitted values for the smoothing splines. The smoothing spline from the second analysis does not capture the changes in share price in recent years but does a good job in the earlier years. The degree of smoothness in the weekly share prices changes over time which presents a challenge for any method that attempts to distill the degree of smoothness in a single parameter.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-aapl-smooth-splines" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aapl-smooth-splines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="reglocal_files/figure-html/fig-aapl-smooth-splines-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-9" data-gallery="quarto-lightbox-gallery-9"><img src="reglocal_files/figure-html/fig-aapl-smooth-splines-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aapl-smooth-splines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.16: Smoothing splines for AAPL close share prices.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;12.1: Simulated data according to <span class="citation" data-cites="Garcia-Portugues2024">García-Portugués (<a href="references.html#ref-Garcia-Portugues2024" role="doc-biblioref">2024</a>)</span>.</span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;12.2: Epanechnikov, tricube and Gaussian kernel functions popular in kernel regression and density estimation. Bandwidth set to 0.5 and 1 for each kernel.</span>
<span class="glightbox-desc lightbox-desc-3">Figure&nbsp;12.8: Polynomial models up to the 5<sup>th</sup> degree.</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;12.9: Piecewise linear model with four interior knots.</span>
<span class="glightbox-desc lightbox-desc-5">Figure&nbsp;12.11: Cubic spline with four interior knots.</span>
<span class="glightbox-desc lightbox-desc-6">Figure&nbsp;12.12: Natural cubic spline with four interior knots.</span>
<span class="glightbox-desc lightbox-desc-7">Figure&nbsp;12.14: Cubic and natural cubic splines with 6 degrees of freedom.</span>
<span class="glightbox-desc lightbox-desc-8">Figure&nbsp;12.15: Weekly AAPL close share prices from January 1996 until January 2024 and dates major products were introduced.</span>
<span class="glightbox-desc lightbox-desc-9">Figure&nbsp;12.16: Smoothing splines for AAPL close share prices.</span>
</div>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Cleveland1979" class="csl-entry" role="listitem">
Cleveland, William S. 1979. <span>“Robust Locally Weighted Regression and Smoothing Scatterplots.”</span> <em>Journal of the American Statistical Association</em> 74 (368): 829–36. <a href="https://doi.org/10.1080/01621459.1979.10481038">https://doi.org/10.1080/01621459.1979.10481038</a>.
</div>
<div id="ref-Garcia-Portugues2024" class="csl-entry" role="listitem">
García-Portugués, E. 2024. <em>Notes for Predictive Modeling</em>. <a href="https://bookdown.org/egarpor/PM-UC3M/">https://bookdown.org/egarpor/PM-UC3M/</a>.
</div>
<div id="ref-hastie_ESL" class="csl-entry" role="listitem">
Hastie, Trevor, Robert Tibshirani, and Jerome Friedman. 2001. <em>The Elements of Statistical Learning</em>. Springer Series in Statistics. New York, NY, USA: Springer New York Inc.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./regdiscrete.html" class="pagination-link" aria-label="Discrete Target Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Discrete Target Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./class_reg.html" class="pagination-link" aria-label="Regression Approach to Classification">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regression Approach to Classification</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Statistical Learning by Oliver Schabenberger</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"loop":false,"openEffect":"zoom","descPosition":"bottom","selector":".lightbox","closeEffect":"zoom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>